hostname: duplicate-ip-address-2
metadata:
  platform: vEOS-lab
is_deployed: true
router_bgp:
  as: '65101'
  router_id: 10.255.0.4
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65101'
    next_hop_self: true
    description: duplicate-ip-address-1
    maximum_routes: 12000
    send_community: all
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    ebgp_multihop: 3
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  neighbors:
  - ip_address: 10.255.1.98
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    peer: duplicate-ip-address-1
    description: duplicate-ip-address-1
  - ip_address: 10.255.255.2
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65100'
    peer: duplicate-ip-address-uplink-switch-router-bgp
    description: duplicate-ip-address-uplink-switch-router-bgp_Ethernet2
  - ip_address: 10.255.0.1
    peer_group: EVPN-OVERLAY-PEERS
    peer: duplicate-ip-address-uplink-switch-router-bgp
    description: duplicate-ip-address-uplink-switch-router-bgp
    remote_as: '65100'
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 172.16.1.102/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
spanning_tree:
  no_spanning_tree_vlan: 4093-4094
vlans:
- id: 4093
  tenant: system
  name: LEAF_PEER_L3
  trunk_groups:
  - LEAF_PEER_L3
- id: 4094
  tenant: system
  name: MLAG_PEER
  trunk_groups:
  - MLAG
vlan_interfaces:
- name: Vlan4093
  description: MLAG_PEER_L3_PEERING
  shutdown: false
  mtu: 9214
  ip_address: 10.255.1.99/31
- name: Vlan4094
  description: MLAG_PEER
  shutdown: false
  ip_address: 10.255.1.67/31
  no_autostate: true
  mtu: 9214
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_PEER_duplicate-ip-address-1_Po3
  type: switched
  shutdown: false
  mode: trunk
  trunk_groups:
  - LEAF_PEER_L3
  - MLAG
ethernet_interfaces:
- name: Ethernet3
  peer: duplicate-ip-address-1
  peer_interface: Ethernet3
  peer_type: mlag_peer
  description: MLAG_PEER_duplicate-ip-address-1_Ethernet3
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 3
    mode: active
- name: Ethernet4
  peer: duplicate-ip-address-1
  peer_interface: Ethernet4
  peer_type: mlag_peer
  description: MLAG_PEER_duplicate-ip-address-1_Ethernet4
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 3
    mode: active
- name: Ethernet1
  peer: duplicate-ip-address-uplink-switch-router-bgp
  peer_interface: Ethernet2
  peer_type: spine
  description: P2P_LINK_TO_DUPLICATE-IP-ADDRESS-UPLINK-SWITCH-ROUTER-BGP_Ethernet2
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 10.255.255.3/31
mlag_configuration:
  domain_id: duplicate-ip-address-router-bgp
  local_interface: Vlan4094
  peer_address: 10.255.1.66
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - origin incomplete
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 10.255.0.4/32
- name: Loopback1
  description: VTEP_VXLAN_Tunnel_Source
  shutdown: false
  ip_address: 10.255.1.4/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.0.0/27 eq 32
  - sequence: 20
    action: permit 10.255.1.0/27 eq 32
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
vxlan_interface:
  Vxlan1:
    description: duplicate-ip-address-2_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback1
      virtual_router_encapsulation_mac_address: mlag-system-id
