# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
# tasks file for dhcp_provisioner

- name: Create required output directories if not present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ structured_dir }}"
    - "{{ eos_config_dir }}"
    - "{{ structured_cvp_dir }}"
  delegate_to: localhost
  run_once: true

- name: Build DHCP intended variables
  ansible.builtin.template:
    src: ztp_configuration.j2
    dest: "{{ structured_cvp_dir }}/ztp_configuration.yml"
    mode: 0664
  delegate_to: localhost
  run_once: true

- name: Include DHCP variables to build dhcpd.conf file
  ansible.builtin.include_vars: "{{ structured_cvp_dir }}/ztp_configuration.yml"
  run_once: true

- name: Start creation/update process.
  tags: [provision]
  ansible.builtin.include_tasks: "./{{ ztp_mode }}.yml"
