anta.tests.connectivity:
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: dc2-leaf1a
      neighbor_port: Ethernet1
      port: Ethernet1
    result_overwrite:
      categories:
      - LLDP Topology
      custom_field: 'local: Ethernet1 - remote: dc2-leaf1a_Ethernet1'
      description: LLDP topology - validate peer and interface
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: dc2-leaf1b
      neighbor_port: Ethernet1
      port: Ethernet2
    result_overwrite:
      categories:
      - LLDP Topology
      custom_field: 'local: Ethernet2 - remote: dc2-leaf1b_Ethernet1'
      description: LLDP topology - validate peer and interface
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: dc2-leaf2a
      neighbor_port: Ethernet1
      port: Ethernet3
    result_overwrite:
      categories:
      - LLDP Topology
      custom_field: 'local: Ethernet3 - remote: dc2-leaf2a_Ethernet1'
      description: LLDP topology - validate peer and interface
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: dc2-leaf2b
      neighbor_port: Ethernet1
      port: Ethernet4
    result_overwrite:
      categories:
      - LLDP Topology
      custom_field: 'local: Ethernet4 - remote: dc2-leaf2b_Ethernet1'
      description: LLDP topology - validate peer and interface
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: dc2-leaf3a.arista.com
      neighbor_port: Ethernet1
      port: Ethernet5
    result_overwrite:
      categories:
      - LLDP Topology
      custom_field: 'local: Ethernet5 - remote: dc2-leaf3a.arista.com_Ethernet1'
      description: LLDP topology - validate peer and interface
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: dc2-leaf3b.arista.com
      neighbor_port: Ethernet1
      port: Ethernet6
    result_overwrite:
      categories:
      - LLDP Topology
      custom_field: 'local: Ethernet6 - remote: dc2-leaf3b.arista.com_Ethernet1'
      description: LLDP topology - validate peer and interface
- VerifyReachability:
    hosts:
    - destination: 10.255.255.105
      repeat: 1
      source: 10.255.255.104
      vrf: default
    result_overwrite:
      categories:
      - IP Reachability
      custom_field: 'Source: dc2-spine1_Ethernet1 - Destination: dc2-leaf1a_Ethernet1'
      description: ip reachability test p2p links
- VerifyReachability:
    hosts:
    - destination: 10.255.255.109
      repeat: 1
      source: 10.255.255.108
      vrf: default
    result_overwrite:
      categories:
      - IP Reachability
      custom_field: 'Source: dc2-spine1_Ethernet2 - Destination: dc2-leaf1b_Ethernet1'
      description: ip reachability test p2p links
- VerifyReachability:
    hosts:
    - destination: 10.255.255.113
      repeat: 1
      source: 10.255.255.112
      vrf: default
    result_overwrite:
      categories:
      - IP Reachability
      custom_field: 'Source: dc2-spine1_Ethernet3 - Destination: dc2-leaf2a_Ethernet1'
      description: ip reachability test p2p links
- VerifyReachability:
    hosts:
    - destination: 10.255.255.117
      repeat: 1
      source: 10.255.255.116
      vrf: default
    result_overwrite:
      categories:
      - IP Reachability
      custom_field: 'Source: dc2-spine1_Ethernet4 - Destination: dc2-leaf2b_Ethernet1'
      description: ip reachability test p2p links
- VerifyReachability:
    hosts:
    - destination: 10.255.255.121
      repeat: 1
      source: 10.255.255.120
      vrf: default
    result_overwrite:
      categories:
      - IP Reachability
      custom_field: 'Source: dc2-spine1_Ethernet5 - Destination: dc2-leaf3a.arista.com_Ethernet1'
      description: ip reachability test p2p links
- VerifyReachability:
    hosts:
    - destination: 10.255.255.125
      repeat: 1
      source: 10.255.255.124
      vrf: default
    result_overwrite:
      categories:
      - IP Reachability
      custom_field: 'Source: dc2-spine1_Ethernet6 - Destination: dc2-leaf3b.arista.com_Ethernet1'
      description: ip reachability test p2p links
anta.tests.hardware:
- VerifyEnvironmentPower:
    states:
    - ok
- VerifyEnvironmentCooling:
    states:
    - ok
- VerifyTemperature: {}
- VerifyTransceiversManufacturers:
    manufacturers:
    - Arista Networks
    - Arastra, Inc.
    - Not Present
anta.tests.interfaces:
- VerifyInterfacesStatus:
    interfaces:
    - interface: Ethernet1
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Ethernet1 - P2P_LINK_TO_DC2-LEAF1A_Ethernet1
      description: Ethernet Interface & Line Protocol == 'up'
- VerifyInterfacesStatus:
    interfaces:
    - interface: Ethernet2
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Ethernet2 - P2P_LINK_TO_DC2-LEAF1B_Ethernet1
      description: Ethernet Interface & Line Protocol == 'up'
- VerifyInterfacesStatus:
    interfaces:
    - interface: Ethernet3
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Ethernet3 - P2P_LINK_TO_DC2-LEAF2A_Ethernet1
      description: Ethernet Interface & Line Protocol == 'up'
- VerifyInterfacesStatus:
    interfaces:
    - interface: Ethernet4
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Ethernet4 - P2P_LINK_TO_DC2-LEAF2B_Ethernet1
      description: Ethernet Interface & Line Protocol == 'up'
- VerifyInterfacesStatus:
    interfaces:
    - interface: Ethernet5
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Ethernet5 - P2P_LINK_TO_DC2-LEAF3A.ARISTA.COM_Ethernet1
      description: Ethernet Interface & Line Protocol == 'up'
- VerifyInterfacesStatus:
    interfaces:
    - interface: Ethernet6
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Ethernet6 - P2P_LINK_TO_DC2-LEAF3B.ARISTA.COM_Ethernet1
      description: Ethernet Interface & Line Protocol == 'up'
- VerifyInterfacesStatus:
    interfaces:
    - interface: Loopback0
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Loopback0 - EVPN_Overlay_Peering
      description: Loopback Interface Status & Line Protocol == 'up'
anta.tests.routing.bgp:
- VerifyBGPSpecificPeers:
    address_families:
    - afi: ipv4
      peers:
      - 10.255.255.105
      safi: unicast
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.255.105'
      description: ip bgp peer state established (ipv4)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: ipv4
      peers:
      - 10.255.255.109
      safi: unicast
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.255.109'
      description: ip bgp peer state established (ipv4)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: ipv4
      peers:
      - 10.255.255.113
      safi: unicast
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.255.113'
      description: ip bgp peer state established (ipv4)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: ipv4
      peers:
      - 10.255.255.117
      safi: unicast
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.255.117'
      description: ip bgp peer state established (ipv4)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: ipv4
      peers:
      - 10.255.255.121
      safi: unicast
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.255.121'
      description: ip bgp peer state established (ipv4)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: ipv4
      peers:
      - 10.255.255.125
      safi: unicast
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.255.125'
      description: ip bgp peer state established (ipv4)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: evpn
      peers:
      - 10.255.128.13
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.128.13'
      description: bgp evpn peer state established (evpn)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: evpn
      peers:
      - 10.255.128.14
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.128.14'
      description: bgp evpn peer state established (evpn)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: evpn
      peers:
      - 10.255.128.15
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.128.15'
      description: bgp evpn peer state established (evpn)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: evpn
      peers:
      - 10.255.128.16
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.128.16'
      description: bgp evpn peer state established (evpn)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: evpn
      peers:
      - 10.255.128.17
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.128.17'
      description: bgp evpn peer state established (evpn)
- VerifyBGPSpecificPeers:
    address_families:
    - afi: evpn
      peers:
      - 10.255.128.18
    result_overwrite:
      categories:
      - BGP
      custom_field: 'bgp_neighbor: 10.255.128.18'
      description: bgp evpn peer state established (evpn)
anta.tests.routing.generic:
- VerifyRoutingProtocolModel:
    model: multi-agent
    result_overwrite:
      categories:
      - BGP
      custom_field: ArBGP
      description: ArBGP is configured and operating
anta.tests.security:
- VerifyAPIHttpsSSL:
    profile: eAPI_SSL_Profile
anta.tests.system:
- VerifyNTP:
    result_overwrite:
      categories:
      - NTP
      custom_field: NTP
      description: Synchronised with NTP server
