anta.tests.connectivity:
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: dc2-leaf1a
      neighbor_port: Ethernet8
      port: Ethernet1
    result_overwrite:
      categories:
      - LLDP Topology
      custom_field: 'local: Ethernet1 - remote: dc2-leaf1a_Ethernet8'
      description: LLDP topology - validate peer and interface
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: dc2-leaf1b
      neighbor_port: Ethernet8
      port: Ethernet2
    result_overwrite:
      categories:
      - LLDP Topology
      custom_field: 'local: Ethernet2 - remote: dc2-leaf1b_Ethernet8'
      description: LLDP topology - validate peer and interface
anta.tests.hardware:
- VerifyEnvironmentPower:
    states:
    - ok
- VerifyEnvironmentCooling:
    states:
    - ok
- VerifyTemperature: {}
- VerifyTransceiversManufacturers:
    manufacturers:
    - Arista Networks
    - Arastra, Inc.
    - Not Present
anta.tests.interfaces:
- VerifyInterfacesStatus:
    interfaces:
    - interface: Ethernet1
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Ethernet1 - DC2-LEAF1A_Ethernet8
      description: Ethernet Interface & Line Protocol == 'up'
- VerifyInterfacesStatus:
    interfaces:
    - interface: Ethernet2
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Ethernet2 - DC2-LEAF1B_Ethernet8
      description: Ethernet Interface & Line Protocol == 'up'
- VerifyInterfacesStatus:
    interfaces:
    - interface: Ethernet5
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Ethernet5 - dc2-leaf1-server1_iLO
      description: Ethernet Interface & Line Protocol == 'up'
- VerifyInterfacesStatus:
    interfaces:
    - interface: Port-Channel1
      protocol_status: up
      state: up
    result_overwrite:
      categories:
      - Interface State
      custom_field: Port-Channel1 - DC2_L3_LEAF1_Po8
      description: Port-Channel Interface & Line Protocol == 'up'
anta.tests.security:
- VerifyAPIHttpsSSL:
    profile: eAPI_SSL_Profile
anta.tests.system:
- VerifyNTP:
    result_overwrite:
      categories:
      - NTP
      custom_field: NTP
      description: Synchronised with NTP server
