# Testing an EVPN VTEP where the default VRF is _not_ EVPN enabled.
# Make sure there is no route-map added to the underlay peer group filtering the evpn prefixes.
# Also make sure the VRF is not configured under interface Vxlan 1
# Minimum config to only test the specific feature.
type: l3leaf
l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 8
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    virtual_router_mac_address: 00:dc:00:00:00:0a
  nodes:
    - name: evpn-vtep-with-default-vrf-not-evpn
      id: 101
      bgp_as: 101

tenants:
  - name: MY_FABRIC
    mac_vrf_vni_base: 10000
    vrfs:
      - name: default
        address_families: []
        vrf_id: 1
        svis:
          - id: 110
            name: SVI-110
            enabled: true
            ip_address_virtual: 10.1.10.1
