type: l3leaf

l3leaf:
  defaults:
    loopback_ipv4_pool: 10.10.0.0/24
    vtep_loopback_ipv4_pool: 10.11.0.0/24
    vtep_loopback: Loopback1
    virtual_router_mac_address: 00:1c:73:00:00:01
    ipvpn_gateway:
      enabled: true
      evpn_domain_id: "65100:10"
      ipvpn_domain_id: "65555:20"
      enable_d_path: true
      maximum_routes: 111
      local_as: "65555.100"
      remote_peers:
        - hostname: SOME-EBGP-PEER
          ip_address: 10.90.90.90
          bgp_as: "65099.900"
        - hostname: SOME-IBGP-PEER
          ip_address: 10.80.80.80
          bgp_as: "65555.100"
  nodes:
    - name: evpn-to-ipvpn-gateway
      id: 1
      bgp_as: "65100.100"

tenants:
  - name: mytenant
    mac_vrf_vni_base: 10000
    vrfs:
      - name: testvrf
        vrf_id: 1
        svis:
          - id: 10
            name: TEST_SVI_VLAN_10
            ip_address_virtual: 10.10.10.10/24
