# Minimum config to only test the specific feature.
mgmt_interface_vrf: MGMT
type: l2leaf
ipv6_mgmt_gateway: 0200::1
l2leaf:
  defaults:
  nodes:
    - name: mgmt_interface_ipv6
      ipv6_mgmt_ip: 0200::105/64
      id: 103
