type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: ntp-settings-1
      mgmt_ip: 192.168.0.2/24

ntp_settings:
  # use_mgmt_interface_vrf is tested in many other places, so here we try with a hardcoded VRF.
  # This will _not_ set the local_interface.
  server_vrf: default
  servers:
    - name: 10.10.10.1
    - name: 10.10.10.2
      burst: true
      iburst: true
      key: 1
      maxpoll: 5
      minpoll: 3
      version: 4
  authenticate: true
  authenticate_servers_only: true
  authentication_keys:
    - id: 1
      hash_algorithm: sha1
      key: someobfuscatedkey
      key_type: 7
  trusted_keys: 1
