---

# Expected result: rd 1.1.1.1:<mac_vrf_id>
overlay_rd_type:
  admin_subfield: 1.1.1.1

# Expected result:
# VLAN rd 8<vlanid>:<vlan_id>
# VRF rd 22:11 (<vrf_vni>:<vrf_id>)
overlay_rt_type:
  admin_subfield: vrf_vni
  vlan_assigned_number_subfield: vlan_id
