---

# Expected result: rd 192.168.254.2:<vlan_id>
overlay_rd_type:
  admin_subfield: vtep_loopback
  vlan_assigned_number_subfield: vlan_id

# Expected result: rt 65002:<vlan_id>
overlay_rt_type:
  admin_subfield: bgp_as
  vlan_assigned_number_subfield: vlan_id
