# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  bgp_graceful_restart:
    documentation_options:
      table: bgp-settings
    description: |
      BGP graceful-restart allows a BGP speaker with separate control plane and data plane processing to continue forwarding traffic during a BGP restart.
      Its neighbors (receiving speakers) may retain routing information from the restarting speaker while a BGP session with it is being re-established, reducing route flapping.
    type: dict
    keys:
      enabled:
        type: bool
        default: false
        required: true
        description: Enable or disable graceful-restart for all BGP peers.
      restart_time:
        type: int
        convert_types:
          - str
        min: 1
        max: 3600
        default: 300
        description: Restart time in seconds.
