# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  cv_topology:
    documentation_options:
      table: cv-topology
    type: list
    # Other future uses of this could be post validation or even input validation to highlight discrepancies
    description: |-
      Generate AVD configurations directly from the given CloudVision topology.
      Activate this feature by setting `use_cv_topology` to `true`.
      Requires `default_interfaces` to be set for the relevant platforms and node types to detect the proper interface roles automatically.
      Neighbor hostnames must match the inventory hostnames of the AVD inventory to be taken into consideration.
    primary_key: hostname
    items:
      type: dict
      keys:
        hostname:
          type: str
        platform:
          type: str
          required: true
        interfaces:
          type: list
          required: True
          primary_key: name
          items:
            type: dict
            keys:
              name:
                type: str
              neighbor:
                type: str
              neighbor_interface:
                type: str
