# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  cvp_ingestauth_key:
    documentation_options:
      table: cloudvision-settings
    type: str
    description: |-
      On-premise CVP ingest auth key. If set, TerminAttr will be configured with key-based authentication for on-premise CVP.
      If not set, TerminAttr will be configured with certificate based authentication:
      - On-premise using token onboarding. Default token path is '/tmp/token'.
      - CVaaS using token-secure onboarding. Default token path is '/tmp/cv-onboarding-token'.
      Token must be copied to the device first.
