# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  default_interfaces:
    documentation_options:
      table: default-interfaces
    type: list
    description: |
      Default uplink, downlink, and MLAG interfaces, which will be used if these interfaces are not defined on a device (either directly or through inheritance).
    items:
      type: dict
      keys:
        types:
          type: list
          required: true
          description: List of node type keys.
          items:
            type: str
        platforms:
          type: list
          required: true
          description: |
            List of platform families.
            This is defined as a Python regular expression that matches the full platform type.
          items:
            type: str
            description: Arista platform family regular expression.
        uplink_interfaces:
          type: list
          description: List of uplink interfaces or uplink interface ranges.
          items:
            type: str
            description: Interface range or interface.
        mlag_interfaces:
          type: list
          description: List of MLAG interfaces or MLAG interface ranges.
          items:
            type: str
            description: Interface range or interface.
        downlink_interfaces:
          type: list
          description: List of downlink interfaces or downlink interface ranges.
          items:
            type: str
            description: Interface range or interface.
