# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  default_igmp_snooping_enabled:
    documentation_options:
      table: system-settings
    description: |
      When set to false, disables IGMP snooping at fabric level and overrides per vlan settings.
    type: bool
    default: true
