# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  design:
    documentation_options:
      table: design
    type: dict
    keys:
      type:
        type: str
        description: |
          By setting the design.type variable, the default node-types and templates described in these documents will be used.
        valid_values:
          - l3ls-evpn
          - mpls
          - l2ls
        default: "l3ls-evpn"
