# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  enable_trunk_groups:
    documentation_options:
      table: fabric-settings
    type: bool
    description: |
      Enable Trunk Group support across eos_designs.
      Warning: Because of the nature of the EOS Trunk Group feature, enabling this is "all or nothing".
      *All* vlans and *all* trunks towards connected endpoints must be using trunk groups as well.
      If trunk groups are not assigned to a trunk, no vlans will be enabled on that trunk.
      See "Details on enable_trunk_groups" below before enabling this feature.
    default: false
