# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  eos_designs_custom_templates:
    documentation_options:
      table: role-custom-templates
    type: list
    items:
      type: dict
      keys:
        template:
          type: str
          description: Template file.
          required: true
        options:
          description: Template options.
          type: dict
          keys:
            list_merge:
              type: str
              description: Merge strategy for lists.
              default: 'append_rp'
            strip_empty_keys:
              type: bool
              description: Filter out keys from the generated output if value is null/none/undefined.
              default: true
