# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  fabric_sflow:
    documentation_options:
      table: fabric-settings
    type: dict
    description: Fabric-wide sFlow settings.
    keys:
      uplinks:
        description: Enable sFlow on all fabric uplinks.
        type: bool
      downlinks:
        description: Enable sFlow on all fabric downlinks.
        type: bool
      endpoints:
        description: Enable sFlow on all endpoints ports.
        type: bool
      l3_edge:
        description: Enable sFlow on all p2p_links defined under l3_edge.
        type: bool
      core_interfaces:
        description: Enable sFlow on all p2p_links defined under core_interfaces.
        type: bool
      mlag_interfaces:
        description: Enable sFlow on all MLAG peer interfaces.
        type: bool
