# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  fabric_name:
    documentation_options:
      table: fabric-topology
    description: Fabric Name, required to match Ansible Group name covering all devices in the Fabric, **must** be an inventory group name.
    type: str
    required: true
