# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  mac_address_table:
    documentation_options:
      table: system-settings
    type: dict
    description: |
      MAC address-table aging time.
      Use to change the EOS default of 300.
    keys:
      aging_time:
        type: int
        convert_types:
          - str
        description: |
          Aging time in seconds 10-1000000.
          Enter 0 to disable aging.
        min: 0
        max: 1000000
