# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  overlay_routing_protocol_address_family:
    documentation_options:
      table: overlay-settings
    type: str
    description: |
      When set to `ipv6`, enable overlay EVPN peering with IPv6 addresses.
      This feature depends on underlay_ipv6 variable. As of today, only RFC5549 is capable to transport IPv6 in the underlay.
    valid_values:
      - ipv4
      - ipv6
    default: ipv4
