# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  overlay_her_flood_list_per_vni:
    documentation_options:
      table: overlay-settings
    type: bool
    description: |
      When using Head-End Replication, configure flood-lists per VNI.
      By default HER will be configured with a common flood-list containing all VTEPs.
      This behavior can be changed to per-VNI flood-lists by setting `overlay_her_flood_list_per_vni: true`.
      This will make `eos_designs` consider configured VLANs per VTEP, and only include the relevant VTEPs to each VNI's flood-list.
    default: false
