# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  overlay_her_flood_list_scope:
    documentation_options:
      table: overlay-settings
    type: str
    description: |
      When using Head-End Replication, set the scope of flood-lists to Fabric or DC.
      By default all VTEPs in the Fabric (part of the inventory group referenced by "fabric_name") are added to the flood-lists.
      This can be changed to all VTEPs in the DC (sharing the same "dc_name" value).
      This is useful if Border Leaf switches are dividing the VXLAN overlay into separate domains.
    valid_values:
      - "fabric"
      - "dc"
    default: "fabric"
