# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  terminattr_ingestgrpcurl_port:
    documentation_options:
      table: cloudvision-settings
    type: int
    convert_types:
      - str
    default: 9910
    description: |-
      Port number used for Terminattr connection to an on-premise CloudVision cluster.
      The port number is always 443 when using CloudVision as a Service, so this value is ignored.
