# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  underlay_rfc5549:
    documentation_options:
      table: fabric-settings
    description: |
      Point to Point Underlay with RFC 5549(eBGP), i.e. IPv6 Unnumbered.
      Requires "underlay_routing_protocol: ebgp".
    type: bool
    default: false
