hostname: BGP-LEAF2
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 172.31.0.1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer: BGP-SPINE1
  peer_interface: Ethernet2
  peer_type: l3spine
  description: BGP-SPINE1_Ethernet2
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: BGP-SPINE2
  peer_interface: Ethernet2
  peer_type: l3spine
  description: BGP-SPINE2_Ethernet2
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet10
  peer: Endpoint
  peer_type: network_port
  description: Endpoint
  shutdown: false
  type: switched
  mode: access
  vlans: '100'
- name: Ethernet11
  peer: Endpoint
  peer_type: network_port
  description: Endpoint
  shutdown: false
  type: switched
  mode: access
  vlans: '100'
port_channel_interfaces:
- name: Port-Channel1
  description: BGP_SPINES_Po2
  type: switched
  shutdown: false
  mode: trunk
  vlans: '100'
vlans:
- id: 100
  name: SVI_100
  tenant: L2LS_BGP
ip_igmp_snooping:
  globally_enabled: true
