hostname: BGP-LEAF1
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 172.31.0.1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer: BGP-SPINE1
  peer_interface: Ethernet1
  peer_type: l3spine
  description: BGP-SPINE1_Ethernet1
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: BGP-SPINE2
  peer_interface: Ethernet1
  peer_type: l3spine
  description: BGP-SPINE2_Ethernet1
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet10
  peer: Endpoint
  peer_type: network_port
  description: Endpoint
  shutdown: false
  type: switched
  mode: access
  vlans: '100'
- name: Ethernet11
  peer: Endpoint
  peer_type: network_port
  description: Endpoint
  shutdown: false
  type: switched
  mode: access
  vlans: '100'
- name: Ethernet12
  peer: IP Phone
  peer_type: network_port
  description: IP Phone
  shutdown: false
  type: switched
  mode: trunk phone
  native_vlan: 100
  phone:
    vlan: 200
    trunk: untagged
- name: Ethernet13
  peer: IP Phone
  peer_type: network_port
  description: IP Phone
  shutdown: false
  type: switched
  mode: trunk phone
  native_vlan: 100
  phone:
    vlan: 200
    trunk: untagged
- name: Ethernet14
  peer: IP Phone with no native VLAN
  peer_type: network_port
  description: IP Phone with no native VLAN
  shutdown: false
  type: switched
  mode: trunk phone
  phone:
    vlan: 200
    trunk: untagged
port_channel_interfaces:
- name: Port-Channel1
  description: BGP_SPINES_Po1
  type: switched
  shutdown: false
  mode: trunk
  vlans: 1,100,200
vlans:
- id: 1
  name: SVI_1
  tenant: L2LS_BGP
- id: 100
  name: SVI_100
  tenant: L2LS_BGP
- id: 200
  name: SVI_200
  tenant: L2LS_BGP
ip_igmp_snooping:
  globally_enabled: true
