hostname: DC1-POD1-L2LEAF2A
metadata:
  platform: vEOS-LAB
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.1.254
- destination_address_prefix: 0.0.0.0/0
  gateway: 172.21.110.1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 8192
  no_spanning_tree_vlan: '4094'
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
  sha512_password: $6$eJ5TvI8oru5i9e8G$R1X/SbtGTk9xoEHEBQASc7SC2nHYmi.crVgp2pXuCXwxsXEA81e4E0cXgQ6kX08fIeQzauqhv2kS.RGJFCon5/
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
eos_cli: "interface Loopback1002\n  description Loopback created from raw_eos_cli under l2leaf node-group RACK2_MLAG\n\ninterface Loopback1111\n
  \ description Loopback created from raw_eos_cli under platform_settings vEOS-LAB\n"
snmp_server:
  location: TWODC_5STAGE_CLOS DC1 DC1_POD1 DC1-POD1-L2LEAF2A
vlans:
- id: 4094
  tenant: system
  name: MLAG_PEER
  trunk_groups:
  - MLAG
- id: 110
  name: Tenant_A_OP_Zone_1
  tenant: Tenant_A
- id: 111
  name: Tenant_A_OP_Zone_2
  tenant: Tenant_A
- id: 112
  name: Tenant_A_OP_Zone_3
  tenant: Tenant_A
- id: 113
  name: SVI_with_no_vxlan
  tenant: Tenant_A
- id: 1102
  name: test_svi
  tenant: Tenant_A
- id: 1100
  name: test_svi
  tenant: Tenant_A
- id: 1101
  name: test_svi
  tenant: Tenant_A
- id: 2500
  name: web-l2-vlan
  tenant: Tenant_A
- id: 2600
  name: web-l2-vlan-2
  tenant: Tenant_A
- id: 2601
  name: l2vlan_with_no_vxlan
  tenant: Tenant_A
- id: 4085
  tenant: system
  name: L2LEAF_INBAND_MGMT
vlan_interfaces:
- name: Vlan4094
  description: MLAG_PEER
  shutdown: false
  ip_address: 172.20.110.2/31
  no_autostate: true
- name: Vlan4085
  description: L2LEAF_INBAND_MGMT
  shutdown: false
  ip_address: 172.21.110.5/24
  type: inband_mgmt
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_PEER_DC1-POD1-L2LEAF2B_Po3
  type: switched
  shutdown: false
  mode: trunk
  service_profile: QOS-PROFILE
  trunk_groups:
  - MLAG
- name: Port-Channel1
  description: RACK2_MLAG_Po3
  type: switched
  shutdown: false
  mode: trunk
  service_profile: QOS-PROFILE
  vlans: 110-113,1100-1102,2500,2600-2601,4085
  mlag: 1
ethernet_interfaces:
- name: Ethernet3
  peer: DC1-POD1-L2LEAF2B
  peer_interface: Ethernet3
  peer_type: mlag_peer
  description: MLAG_PEER_DC1-POD1-L2LEAF2B_Ethernet3
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 3
    mode: active
- name: Ethernet4
  peer: DC1-POD1-L2LEAF2B
  peer_interface: Ethernet4
  peer_type: mlag_peer
  description: MLAG_PEER_DC1-POD1-L2LEAF2B_Ethernet4
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 3
    mode: active
- name: Ethernet1
  peer: DC1.POD1.LEAF2A
  peer_interface: Ethernet3
  peer_type: l3leaf
  description: DC1.POD1.LEAF2A_Ethernet3
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: DC1-POD1-LEAF2B
  peer_interface: Ethernet3
  peer_type: l3leaf
  description: DC1-POD1-LEAF2B_Ethernet3
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
mlag_configuration:
  domain_id: RACK2_MLAG
  local_interface: Vlan4094
  peer_address: 172.20.110.3
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
ip_igmp_snooping:
  globally_enabled: true
