### Domain Lookup ###
ip_domain_lookup:
  source_interfaces:
    - name: Management0
      vrf: mgt
    - name: Loopback0
    # Note there is no value here. This is valid with the current data model, but triggered an issue with convert_dicts filter.
    # So this is added to ensure we catch regression.

### Name Servers ###
ip_name_servers:
  # no VRF
  - ip_address: 10.10.128.10
  # no VRF priority
  - ip_address: 10.10.129.10
    priority: 0
  # Same DNS management VRF
  - ip_address: 10.10.128.10
    vrf: mgmt
  # Same DNS different VRF and priority
  - ip_address: 10.10.128.10
    vrf: TEST
    priority: 3

### DNS Domain ###
dns_domain: test.local

### NTP Servers ###
ntp:
  local_interface:
    name: Management0
    vrf: mgt
  servers:
    - name: 10.10.111.1
      preferred: True
      vrf: mgt
    - name: 10.10.111.2
      vrf: mgt
  authenticate_servers_only: true
  authentication_keys:
    - id: 1
      hash_algorithm: "md5"
      key: "044F0E151B"
    - id: 2
      hash_algorithm: "sha1"
      key: "15060E1F10"
  trusted_keys: "1-2"
