---
# Verify that sensitive data is replaced by `<removed>`
eos_cli_config_gen_configuration:
  hide_passwords: true

tacacs_servers:
  hosts:
    - host: 10.10.10.157
      key: 071B245F5A

radius_server:
  hosts:
    - host: 10.10.10.158
      key: 071B245F5A

### AAA Root ###
aaa_root:
  secret:
    sha512_password: dsakjlhfqwereDSAFWE346543dfgsG

### Local Users ###
local_users:
  - name: ansible
    sha512_password: $6$.I7/ZR/zlLIUv8fr$vR/JvLTbq5amMt6Y1SE4CKlPDv/AzJYlFYHkUZ17BDovm0Oi4aLdBULe1EmZ0Y9xKjVLMKpxCSKmlrAioDxbQ0

### Enable Password ###
enable_password:
  hash_algorithm: sha512
  key: "$6$nXycSRhVPaxRINPL$tM1MNjjRCbFD5di4XWsj8CPkm8Pdwmf9fVqRV015y3DXD4t1vi8CAWQpFP8Vbi9Y2i7.JuFey5UaafXvI6quD1"

## Routing - BGP ###
router_bgp:
  as: 65100
  router_id: 10.50.64.15
  peer_groups:
    - name: IPV4-UNDERLAY
      remote_as: 65000
      password: "dt5J2fw8tymeDFPyoYLB3w=="
  vrfs:
    - name: BLAH
      neighbors:
        - ip_address: 10.50.2.1
          remote_as: 65000
          password: CY0aYXfSb24=

### IP Security ###
ip_security:
  profiles:
    - name: Profile-1
      shared_key: 12312312313213AA
