### IP Security ###
ip_security:
  ike_policies:
    - name: IKE-1
      local_id: 192.168.100.1
      ike_lifetime: 24
      encryption: aes256
      dh_group: 20
    - name: IKE-2
  sa_policies:
    - name: SA-1
      esp:
        encryption: aes128
      pfs_dh_group: 14
    - name: SA-2
      esp:
        encryption: aes128
      pfs_dh_group: 14
    - name: SA-3
      esp:
        integrity: disabled
        encryption: disabled
      pfs_dh_group: 17
  profiles:
    - name: Profile-1
      ike_policy: IKE-1
      sa_policy: SA-1
      connection: start
      # Need real one
      shared_key: 12312312313213AA
      dpd:
        interval: 42
        time: 666
        action: clear
      mode: transport
    - name: Profile-2
      sa_policy: SA-2
      connection: start
      # Need real one
      shared_key: 1231231231321AA
      mode: tunnel
  key_controller:
    profile: Profile-1
