management_api_gnmi:
  provider: eos-native
  transport:
    grpc:
      - name: MGMT
        vrf: MGMT
        ip_access_group: ACL-GNMI
      - name: MONITORING
        vrf: MONITORING
        port: 6031
