### Management Security ###
management_security:
  entropy_source: hardware
  password:
    minimum_length: 17
    encryption_key_common: true
    encryption_reversible: aes-256-gcm
    policies:
      - name: AVD_POLICY
        minimum:
          digits: 1
          length: 2
          lower: 3
          special: 4
          upper: 5
        maximum:
          repetitive: 6
          sequential: 7
  ssl_profiles:
    - name: tls-versions-profile
      tls_versions: "1.0 1.1"
    - name: cipher-list-profile
      cipher_list: ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384
    - name: certificate-profile
      certificate:
        file: eAPI.crt
        key: eAPI.key
      certificate_revocation_lists:
        - intermediate.crl
        - ca.crl
    - name: tls-single-version-profile-as-string
      tls_versions: "1.1"
    - name: tls-single-version-profile-as-float
      tls_versions: 1.0
    - name: test1-trust-cert
      trust_certificate:
        certificates:
          - test-trust1.crt
          - test-trust2.crt
        requirement:
          basic_constraint_ca: true
        policy_expiry_date_ignore: true
    - name: test1-chain-cert
      chain_certificate:
        certificates:
          - test-chain-cert1.crt
          - test-chain-cert2.crt
        requirement:
          basic_constraint_ca: true
    - name: test2-trust-cert
      trust_certificate:
        requirement:
          hostname_fqdn: true
        system: true
    - name: test2-chain-cert
      chain_certificate:
        requirement:
          include_root_ca: true
