# Management API HTTP
management_api_http:
  enable_http: false
  enable_https: true
  https_ssl_profile: SSL_PROFILE
  default_services: true
  enable_vrfs:
    - name: default
      access_group: ACL-API
    - name: MGMT
      access_group: ACL-API
  protocol_https_certificate:
    certificate: <cert_string>
    private_key: <private_key>

# Standard ACLs
standard_access_lists:
  - name: ACL-API
    sequence_numbers:
      - sequence: 10
        action: "permit 10.0.0.0/8"
      - sequence: 20
        action: "permit 100.0.0.0/8"
