### IPv4 Prefix-Lists ###
dynamic_prefix_lists:
  - name: DYNAMIC_PREFIX_LIST_NAME_3
    match_map: Test_2
    prefix_list:
      ipv4: IPV4_PREFIX_LIST
      ipv6: IPV6_PREFIX_LIST
  - name: DYNAMIC_PREFIX_LIST_NAME_1
    match_map: Test_1
    prefix_list:
      ipv4: IPV4_PREFIX_LIST
  - name: DYNAMIC_PREFIX_LIST_NAME_2
    match_map: Test_2
    prefix_list:
      ipv6: IPV6_PREFIX_LIST

### IPv4 Prefix-Lists ###
prefix_lists:
  - name: PL-LOOPBACKS-EVPN-OVERLAY
    sequence_numbers:
      - sequence: 10
        action: "permit 192.168.255.0/24 eq 32"
      - sequence: 20
        action: "permit 192.168.254.0/24 eq 32"

  # prefix_list without sequence_numbers
  - name: PL-IPV4-LOOPBACKS

### IPv6 Prefix-lists ###
ipv6_prefix_lists:
  - name: PL-IPV6-LOOPBACKS
    sequence_numbers:
      - sequence: 10
        action: permit 1b11:3a00:22b0:0082::/64 eq 128
