router_bgp:
  as: 65001
  router_id: 1.0.1.1
  address_family_ipv4:
    peer_groups:
      - name: FOOBAR
        activate: true
        next_hop:
          address_family_ipv6:
            enabled: true
            originate: true
  address_family_ipv6:
    peer_groups:
      - name: FOOBAR
        activate: false
  address_family_ipv4_multicast:
    peer_groups:
      - name: FOOBAR
        activate: true
  address_family_ipv6_multicast:
    peer_groups:
      - name: FOOBAR
        activate: false
  address_family_flow_spec_ipv4:
    peer_groups:
      - name: FOOBAR
        activate: true
  address_family_flow_spec_ipv6:
    peer_groups:
      - name: FOOBAR
        activate: false
  vrfs:
    - name: VRF01
      address_family_ipv4:
        bgp:
          missing_policy:
            direction_in_action: deny
            direction_out_action: permit
          additional_paths:
            install_ecmp_primary: true
            receive: true
            send:
              ecmp_limit: 4
        neighbors:
          - ip_address: 1.2.3.4
            activate: true
            route_map_in: FOO
            route_map_out: BAR
        networks:
          - prefix: 2.3.4.0/24
            route_map: BARFOO
      address_family_ipv6:
        bgp:
          missing_policy:
            direction_in_action: deny-in-out
            direction_out_action: deny-in-out
          additional_paths:
            install: true
            receive: true
            send:
              any: true
        neighbors:
          - ip_address: aa::1
            activate: true
            route_map_in: FOO
            route_map_out: BAR
        networks:
          - prefix: aa::/64
      address_family_ipv4_multicast:
        bgp:
          missing_policy:
            direction_in_action: permit
            direction_out_action: permit
          additional_paths:
            receive: true
        neighbors:
          - ip_address: 1.2.3.4
            activate: false
            route_map_in: FOO
            route_map_out: BAR
        networks:
          - prefix: 239.0.0.0/24
            route_map: BARFOO
      address_family_ipv6_multicast:
        bgp:
          missing_policy:
            direction_in_action: deny
            direction_out_action: deny
        neighbors:
          - ip_address: aa::1
            activate: false
        networks:
          - prefix: ff08:1::/64
      address_family_flow_spec_ipv4:
        bgp:
          missing_policy:
            direction_in_action: permit
            direction_out_action: permit
        neighbors:
          - ip_address: 1.2.3.4
            activate: true
      address_family_flow_spec_ipv6:
        bgp:
          missing_policy:
            direction_in_action: permit
            direction_out_action: deny
        neighbors:
          - ip_address: aa::1
            activate: true

    - name: VRF02
      address_family_ipv4:
        bgp:
          additional_paths:
            send:
              backup: true
      address_family_ipv6:
        bgp:
          additional_paths:
            send:
              limit: 3

    - name: VRF03
      address_family_ipv4:
        bgp:
          additional_paths:
            send:
              ecmp: true
