router_bgp:
  as: 65101
  router_id: 192.168.255.3
  updates:
    wait_for_convergence: true
    wait_install: true
  distance:
    external_routes: 20
    internal_routes: 200
    local_routes: 200
  graceful_restart:
    enabled: true
    restart_time: 555
    stalepath_time: 666
  graceful_restart_helper:
    enabled: true
    restart_time: 888
    long_lived: true
  maximum_paths:
    paths: 32
    ecmp: 32
  bgp:
    default:
      ipv4_unicast: false
      ipv4_unicast_transport_ipv6: false
    route_reflector_preserve_attributes:
      enabled: true
      always: true
    bestpath:
      d_path: true
  listen_ranges:
      # should render
    - prefix: 10.10.10.0/24
      peer_group: my-peer-group1
      peer_filter: my-peer-filter
      # It shouldn't render because neither peer-filter nor as-filter are defined
    - prefix: 11.10.10.0/24
      peer_group: my-peer-group2
      # should render with remote-as filter
    - prefix: 12.10.10.0/24
      peer_id_include_router_id: true
      peer_group: my-peer-group3
      remote_as: 65444
      # should render with peer-filter because of precedence
    - prefix: 13.10.10.0/24
      peer_group: my-peer-group4
      peer_filter: my-peer-filter
      remote_as: 65444
  peer_groups:
    - name: test-link-bandwidth1
      link_bandwidth:
        enabled: true
        default: 100G
    - name: test-link-bandwidth2
      link_bandwidth:
        enabled: true
    - name: test-passive
      passive: true
    - name: test-session-tracker
      session_tracker: ST2
  aggregate_addresses:
    - prefix: 1.1.1.0/24
      advertise_only: true
    - prefix: 2.2.1.0/24
    - prefix: 1.12.1.0/24
      as_set: true
      summary_only: true
      attribute_map: RM-ATTRIBUTE
      match_map: RM-MATCH
      advertise_only: true
  redistribute_routes:
    - source_protocol: ospf
      include_leaked: true
    - source_protocol: bgp
      route_map: RM-REDISTRIBUTE-BGP
      # this should not do anything as leaked is generated when source protocol is bgp
      include_leaked: true
  address_family_ipv4:
    networks:
      - prefix: 10.0.0.0/8
      - prefix: 172.16.0.0/12
      - prefix: 192.168.0.0/16
        route_map: RM-FOO-MATCH
    peer_groups:
      - name: foo
        prefix_list_in: PL-BAR-v4-IN
        prefix_list_out: PL-BAR-v4-OUT
        default_originate:
          always: true
          route_map: RM-FOO-MATCH
    neighbors:
      - ip_address: 192.0.2.1
        prefix_list_in: PL-FOO-v4-IN
        prefix_list_out: PL-FOO-v4-OUT
  address_family_ipv6:
    networks:
      - prefix: 2001:db8:100::/40
      - prefix: 2001:db8:200::/40
        route_map: RM-BAR-MATCH
    peer_groups:
      - name: baz
        prefix_list_in: PL-BAR-v6-IN
        prefix_list_out: PL-BAR-v6-OUT
    neighbors:
      - ip_address: 2001:db8::1
        prefix_list_in: PL-FOO-v6-IN
        prefix_list_out: PL-FOO-v6-OUT
    redistribute_routes:
      - source_protocol: static
        route_map: RM-IPV6-STATIC-TO-BGP
      - source_protocol: ospf
        include_leaked: true
      - source_protocol: bgp
        route_map: RM-REDISTRIBUTE-BGP
        # this should not do anything as leaked is generated when source protocol is bgp
        include_leaked: true
  neighbors:
    - ip_address: 192.0.3.1
      remote_as: 65432
      send_community: all
      passive: true
      link_bandwidth:
        enabled: true
        default: 100G
      default_originate:
        enabled: true
        always: true
      rib_in_pre_policy_retain:
        enabled: true
      as_path:
        remote_as_replace_out: true
        prepend_own_disabled: true
      session_tracker: ST1
      # Testing bfd true OUTSIDE a peer group that should render
      bfd: true
    - ip_address: 192.0.3.2
      remote_as: 65433
      send_community: extended
      maximum_routes: 10000
      link_bandwidth:
        enabled: true
      default_originate:
        enabled: true
        route_map: RM-FOO-MATCH3
        always: false
      rib_in_pre_policy_retain:
        enabled: true
        all: true
      # Testing bfd false OUTSIDE a peer group that should NOT render
      bfd: false
    - ip_address: 192.0.3.3
      remote_as: 65434
      send_community: standard
      rib_in_pre_policy_retain:
        enabled: true
        all: false
      # Test no config generation
      default_originate:
    - ip_address: 192.0.3.4
      remote_as: 65435
      send_community: large
      default_originate:
        enabled: false
      rib_in_pre_policy_retain:
        enabled: false
    - ip_address: 192.0.3.5
      remote_as: 65436
      description: test_ebgp_multihop
      send_community: standard
      ebgp_multihop: 2
      maximum_routes: 12000
    - ip_address: 192.0.3.6
      remote_as: 65437
      description: test_remove_private_as
      remove_private_as:
        enabled: true
      remove_private_as_ingress:
        enabled: true
      route_reflector_client: false
    - ip_address: 192.0.3.7
      remote_as: 65438
      description: test_remove_private_as_all
      remove_private_as:
        enabled: true
        all: true
        replace_as: true
      remove_private_as_ingress:
        enabled: true
        replace_as: true
      route_reflector_client: true
    # Testing bfd true IN a peer group that should render
    - ip_address: 192.0.3.8
      peer_group: TEST
      bfd: true
      remote_as: 65438
    # Testing bfd false IN a peer group that should render
    - ip_address: 192.0.3.9
      peer_group: TEST
      bfd: false
      remote_as: 65438
  neighbor_interfaces:
    - name: Ethernet2
      peer_group: PG-FOO-v4
      remote_as: 65102
    - name: Ethernet3
      peer_group: PG-FOO-v4
      peer_filter: PF-BAR-v4
  session_trackers:
    - name: ST1
      recovery_delay: 666
    - name: ST2
      recovery_delay: 42
