### Routing - BGP vpn-ipv4 ###
router_bgp:
  as: 65103
  router_id: 192.168.255.3
  peer_groups:
    - name: SR-TE-PG-1
      remote_as: 65000
    - name: SR-TE-PG-2
      remote_as: 65000
  neighbors:
    - ip_address: 192.168.42.42
      remote_as: 65004
    - ip_address: 2001:db8::dead:beef:cafe
      remote_as: 65004
  address_family_ipv4_sr_te:
    peer_groups:
      - name: SR-TE-PG-1
        activate: true
        route_map_in: RM-SR-TE-PEER-IN4
        route_map_out: RM-SR-TE-PEER-OUT4
    neighbors:
      - ip_address: 192.168.42.42
        activate: true
        route_map_in: RM-SR-TE-PEER-IN4
        route_map_out: RM-SR-TE-PEER-OUT4
  address_family_ipv6_sr_te:
    peer_groups:
      - name: SR-TE-PG-2
        activate: true
        route_map_in: RM-SR-TE-PEER-IN6
        route_map_out: RM-SR-TE-PEER-OUT6
    neighbors:
      - ip_address: 2001:db8::dead:beef:cafe
        activate: true
        route_map_in: RM-SR-TE-PEER-IN6
        route_map_out: RM-SR-TE-PEER-OUT6
