tcam_profile:
  system: traffic_policy
  profiles:
    - name: traffic_policy
      config: "{{ lookup('file', '{{ root_dir }}/inventory/TCAM_TRAFFIC_POLICY.conf') }}"
    - name: MY_TCAM_PROFILE
      source: "flash:/TCAM_PROFILES/MY_TCAM_PROFILE.conf"
