### Daemon TerminAttr
daemon_terminattr:
  clusters:
    - name: DC1
      cvaddrs:
        - 10.20.20.1:9910
      cvauth:
        method: "certs"
        cert_file: "/persist/secure/ssl/terminattr/DC1/certs/client.crt"
        key_file: "/persist/secure/ssl/terminattr/DC1/keys/client.key"
        ca_file: "/persist/secure/ssl/terminattr/DC1/certs/ca.crt"
      cvvrf: mgt
      cvsourceintf: Loopback10
    - name: DC2
      cvaddrs:
        - 10.30.30.1:9910
      cvauth:
        method: "certs"
        cert_file: "/persist/secure/ssl/terminattr/DC2/certs/client.crt"
        key_file: "/persist/secure/ssl/terminattr/DC2/keys/client.key"
        ca_file: "/persist/secure/ssl/terminattr/DC2/certs/ca.crt"
      cvvrf: mgt
      cvsourceintf: Vlan500
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
