daemon_terminattr:
  cvaddrs:
    - 192.0.2.1:9910
    - 192.0.2.2:9910
    - 192.0.2.3:9910
  cvauth:
    method: "token"
    token_file: "/tmp/token"
  cvvrf: mgt
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
