### Daemon TerminAttr
daemon_terminattr:
  cvaddrs:
    - 10.10.10.8:9910
    - 10.10.10.9:9910
    - 10.10.10.10:9910
  cvauth:
    method: "certs"
    cert_file: "/persist/secure/ssl/terminattr/primary/certs/client.crt"
    key_file: "/persist/secure/ssl/terminattr/primary/keys/client.key"
    ca_file: "/persist/secure/ssl/terminattr/primary/certs/ca.crt"
  cvvrf: mgt
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
