---
- name: Converge
  hosts: TOOLS
  gather_facts: true
  tasks:
    - name: Create local output folders
      ansible.builtin.import_role:
        name: arista.avd.build_output_folders
      run_once: true
    - name: Generate intended variables
      ansible.builtin.import_role:
        name: arista.avd.dhcp_provisioner
