### BGP Groups ###

# Testing bgp_groups as dict of dict
# Dict type is deprecated in 4.0.0. To be removed in 5.0.0
bgp_groups:
  foo:
    neighbors:
      - fe80::1
      - 169.254.1.1
  bar:
    neighbors:
      - peer-group-baz
    bgp_maintenance_profiles:
      - downlink-neighbors
    vrf: red
