### Domain Lookup ###
ip_domain_lookup:
  # Testing source_interfaces as dict of dict
  # Dict type is deprecated in 4.0.0. To be removed in 5.0.0
  source_interfaces:
    Management0:
      vrf: mgt
    Loopback0:
    # Note there is no value here. This is valid with the current data model, but triggered an issue with convert_dicts filter.
    # So this is added to ensure we catch regression.
