---
### Port-Channel Interfaces ###

# Testing port_channel_interfaces as dict of dict
# Dict type is deprecated in 4.0.0. To be removed in 5.0.0
port_channel_interfaces:
  # Testing deprecated esi and rt variables on port-channel interfaces/subinterfaces
  Port-Channel1:
    description: SRV01_bond0
    vlans: 2-3000
    mode: trunk
    esi: 0000:0000:0404:0404:0303
    rt: 04:04:03:03:02:02
    lacp_id: 0303.0202.0101

  Port-Channel2:
    description: Flexencap Port-Channel
    type: routed
  Port-Channel2.1000:
    type: l2dot1q
    description: L2 Subinterface
    vlan_id: 1000
    encapsulation_vlan:
      client:
        dot1q:
          vlan: 100
      network:
        client: true
    esi: 0000:0000:0303:0202:0101
    rt: 03:03:02:02:01:01
    lacp_id: 0303.0202.0101

  Port-Channel51:
    description: ipv6_prefix
    vlans: 1-500
    mode: trunk
    # Testing ipv6_nd_prefixes as dict of dict
    # Dict type is deprecated in 4.0.0. To be removed in 5.0.0
    ipv6_nd_prefixes:
      a1::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true

  Port-Channel100:
    type: routed
    logging:
      event:
        link_status: true
