### Standard Access-Lists ###

# Testing standard_access_lists as dict of dict
# Dict type is deprecated in 4.0.0. To be removed in 5.0.0
standard_access_lists:
  ACL-API:
    # Testing sequence_numbers as dict of dict
    # Dict type is deprecated in 4.0.0. To be removed in 5.0.0
    sequence_numbers:
      10:
        action: "remark ACL to restrict access to switch API to CVP and Ansible"
      20:
        action: "permit host 10.10.10.10"
      30:
        action: "permit host 10.10.10.11"
      40:
        action: "permit host 10.10.10.12"
