---
### Virtual Source NAT VRFs ###

# Testing virtual_source_nat_vrfs as dict of dict
# Dict type is deprecated in 4.0.0. To be removed in 5.0.0
virtual_source_nat_vrfs:
  TEST_01:
    ip_address: 1.1.1.1
  TEST_02:
    ip_address: 1.1.1.2
