### VLAN Interfaces ###

# Testing vlan_interfaces as dict of dict
# Dict type is deprecated in 4.0.0. To be removed in 5.0.0
vlan_interfaces:
  Vlan1:
    description: test ipv6_address_virtual
    ipv6_enable: true
    # Testing ipv6_address_virtual alone
    # ipv6_address_virtual deprecated in 4.0.0. To be removed in 5.0.0
    ipv6_address_virtual: fc00:10:10:1::1/64

  Vlan2:
    description: test ipv6_address_virtual and ipv6_address_virtuals
    ipv6_enable: true
    ipv6_address: 1b11:3a00:22b0:5200::15/64
    ipv6_nd_managed_config_flag: true
    # Testing ipv6_nd_prefixes as dict of dict
    # Dict type is deprecated in 4.0.0. To be removed in 5.0.0
    ipv6_nd_prefixes:
      1b11:3a00:22b0:5200::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true
    # Testing ipv6_address_virtual in combination with the new ipv6_address_virtuals to see that all three are configured
    # ipv6_address_virtual deprecated in 4.0.0. To be removed in 5.0.0
    ipv6_address_virtual: fc00:10:10:2::1/64
    ipv6_address_virtuals:
      - fc00:10:11:2::1/64
      - fc00:10:12:2::1/64

  Vlan3:
    description: test ipv6_address_virtual
    ipv6_enable: true
    ipv6_address: 1b11:3a00:22b3:5200::15/64
    # Testing ipv6_virtual_router_address
    # ipv6_virtual_router_address deprecated in 4.0.0. To be removed in 5.0.0
    ipv6_virtual_router_address: fc00:10:10:3::1/64

  Vlan42:
    description: SVI Description
    shutdown: false
    ip_address_virtual: 10.10.42.1/24
    # Testing ip_helpers as dict of dict
    # Dict type is deprecated in 4.0.0. To be removed in 5.0.0
    ip_helpers:
      10.10.96.151:
        source_interface: Loopback0
      10.10.96.150:
        source_interface: Loopback0
      10.10.64.150:
        source_interface: Loopback0
