### VxLAN interface ###

vxlan_interface:
  Vxlan1:
    vxlan:
      # Testing vlans as dict of dict
      # Dict type is deprecated in 4.0.0. To be removed in 5.0.0
      vlans:
        110:
          vni: 10110
          multicast_group: 239.9.1.4
        111:
          vni: 10111
          flood_vteps:
            - 10.1.1.10
            - 10.1.1.11
        112:
          multicast_group: 239.9.1.6
      # Testing vlans as dict of dict
      # Dict type is deprecated in 4.0.0. To be removed in 5.0.0
      vrfs:
        Tenant_A_OP_Zone:
          vni: 10
          multicast_group: 232.0.0.10
        Tenant_A_WEB_Zone:
          vni: 11
