# DC1 Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs

tenants:
  - name: fake_tenant
    mac_vrf_vni_base: 20000
    vrfs:
      - name: Tenant_B_OP_Zone
        vrf_vni: 20
        svis:
          - id: 210
            name: Tenant_B_OP_Zone_1
            tags: ['opzone']
            enabled: True
            ip_address_virtual: 10.2.10.1/24
