hostname: host2
is_deployed: true
router_bgp:
  as: '102'
  router_id: 10.42.0.102
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  - name: MPLS-OVERLAY-PEERS
    type: mpls
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    remote_as: '102'
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: MPLS-OVERLAY-PEERS
      activate: false
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  address_family_evpn:
    neighbor_default:
      encapsulation: mpls
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
- name: TENANT_B_WAN
  tenant: TENANT_B
  ip_routing: true
  ipv6_routing: true
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
loopback_interfaces:
- name: Loopback0
  description: MPLS_Overlay_peering
  shutdown: false
  ip_address: 10.42.0.102/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.42.0.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
vlans:
- id: 110
  name: Tenant_A_OP_Zone_1
  tenant: TENANT_B
- id: 111
  name: Tenant_A_OP_Zone_2
  tenant: TENANT_B
- id: 160
  name: Tenant_A_VMOTION
  tenant: TENANT_B
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
vlan_interfaces:
- name: Vlan110
  tenant: TENANT_B
  description: Tenant_A_OP_Zone_1
  shutdown: false
  ipv6_enable: true
  ipv6_address_virtuals:
  - 2001:db8:413::1/64
  vrf: TENANT_B_WAN
  ip_helpers:
  - ip_helper: 1.1.1.1
    source_interface: lo100
    vrf: MGMT
- name: Vlan111
  tenant: TENANT_B
  tags:
  - opzone
  description: Tenant_A_OP_Zone_2
  shutdown: false
  ipv6_enable: true
  ipv6_address_virtuals:
  - 2001:db8:310::1/64
  - 2001:db8:311::1/64
  vrf: TENANT_B_WAN
  ip_helpers:
  - ip_helper: 1.1.1.1
    source_interface: lo100
    vrf: MGMT
