---
- name: Converge
  hosts: test-hosts
  gather_facts: false
  connection: local
  vars:
    tacacs_key_set_as_play_var: "071B245F5A"
  tasks:

    - name: Generate device intended config and documentation
      delegate_to: 127.0.0.1
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
