---
scenario:
  converge_sequence:
    - converge
  test_sequence:
    - converge
    - idempotence
  cleanup_sequence:
    - destroy
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
  options:
    managed: false
platforms:
  - name: dummy
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n
      duplicate_dict_key: error
  playbooks:
    converge: '../../examples/dual-dc-l3ls/build.yml'
  ansible_args:
    - --inventory
    - ${MOLECULE_SCENARIO_DIRECTORY}/../../examples/dual-dc-l3ls/inventory.yml
    - --extra-vars
    - "avd_data_validation_mode=error"
    - --extra-vars
    - "avd_data_conversion_mode=error"
verifier:
  name: ansible
