# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---

# NTP Status Tests

- name: Gather ntp status
  arista.eos.eos_command:
    commands: "show ntp status"
  register: ntp_status
  tags:
    - ntp

- name: Validate ntp status
  delegate_to: localhost
  ansible.builtin.assert:
    that:
      - ntp_status.stdout[0] | regex_search('synchronised to NTP server')
    fail_msg: "Not synchronised to NTP server"
    quiet: true
  ignore_errors: "{{ eos_validate_state_validation_mode_loose }}"
  register: ntp_status_results
  tags:
    - ntp
