# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---

# Validation reports

- name: Generate Results (Set eos_validate_state_report)
  arista.avd.yaml_templates_to_facts:
    templates:
      - template: generate_state_report_results.j2
  delegate_to: localhost
  run_once: true
  changed_when: false # yaml_template_to_facts always return changes in that case which break idempotency falsely
  tags:
    - always
    - report

- name: Create Validation report - CSV
  ansible.builtin.template:
    src: validate_state_report-csv.j2
    dest: "{{ eos_validate_state_csv_report_path }}"
    mode: 0664
  delegate_to: localhost
  run_once: true
  when: validation_report_csv | bool
  tags:
    - always
    - report

- name: Create Validation report - Markdown
  ansible.builtin.template:
    src: validate_state_report-md.j2
    dest: "{{ eos_validate_state_md_report_path }}"
    mode: 0664
  delegate_to: localhost
  run_once: true
  when: validation_report_md | bool
  tags:
    - always
    - report
