---

scenario:
  create_sequence:
    - dependency
    - prepare
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
  cleanup_sequence:
    - destroy
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: dummy
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
      command_warnings: False
  inventory:
    links:
      hosts: 'inventory/hosts.yml'
      group_vars: 'inventory/group_vars/'
      host_vars: 'inventory/host_vars/'
verifier:
  name: ansible
