# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  aaa_accounting:
    type: dict
    keys:
      exec:
        type: dict
        keys:
          console:
            type: dict
            keys:
              type:
                type: str
                valid_values: ["none", "start-stop", "stop-only"]
              group:
                description: Group Name
                type: str
              logging:
                type: bool
          default:
            type: dict
            keys:
              type:
                type: str
                valid_values: ["none", "start-stop", "stop-only"]
              group:
                description: Group Name
                type: str
              logging:
                type: bool
      system:
        type: dict
        keys:
          default:
            type: dict
            keys:
              type:
                type: str
                valid_values: ["none", "start-stop", "stop-only"]
              group:
                description: Group Name
                type: str
      dot1x:
        type: dict
        keys:
          default:
            type: dict
            keys:
              type:
                type: str
                valid_values: ["start-stop", "stop-only"]
              group:
                description: Group Name
                type: str
      commands:
        type: dict
        keys:
          console:
            type: list
            items:
              type: dict
              keys:
                commands:
                  type: str
                  convert_types:
                  - int
                  description: "Privelege level 'all' or 0-15"
                type:
                  type: str
                  valid_values: ["none", "start-stop", "stop-only"]
                group:
                  description: Group Name
                  type: str
                logging:
                  type: bool
          default:
            type: list
            items:
              type: dict
              keys:
                commands:
                  type: str
                  convert_types:
                  - int
                  description: "Privelege level 'all' or 0-15"
                type:
                  type: str
                  valid_values: ["none", "start-stop", "stop-only"]
                group:
                  description: Group Name
                  type: str
                logging:
                  type: bool
