# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  access_lists:
    type: list
    primary_key: name
    convert_types:
      - dict
    display_name: IP Extended Access-Lists (legacy model)
    items:
      type: dict
      keys:
        name:
          type: str
          description: Access-list Name
          convert_types: [ int ]
        counters_per_entry:
          type: bool
        sequence_numbers:
          type: list
          required: true
          primary_key: sequence
          convert_types:
            - dict
          items:
            type: dict
            keys:
              sequence:
                type: int
                description: Sequence ID
                convert_types:
                  - str
              action:
                type: str
                required: true
                description: |
                  Action as string
                  Example: "deny ip any any"
