# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  event_handlers:
    type: list
    description: |
      Gives the ability to monitor and react to Syslog messages.
      Event Handlers provide a powerful and flexible tool that can be used to apply self-healing actions,
      customize the system behavior, and implement workarounds to problems discovered in the field.
    primary_key: name
    convert_types:
    - dict
    items:
      type: dict
      keys:
        name:
          type: str
          description: Event Handler Name
        action_type:
          type: str
          valid_values: ["bash", "increment", "log"]
        action:
          type: str
          description: |
            Command to execute
        delay:
          type: int
          convert_types:
          - str
          description: |
            Event-handler delay in seconds
        trigger:
          type: str
          description: |
            Configure event trigger condition.
          valid_values:
          - on-boot
          - on-logging
          - on-startup-config
        regex:
          type: str
          description: |
            Regular expression to use for searching log messages. Required for on-logging trigger
        asynchronous:
          type: bool
          default: False
          description: |
            Set the action to be non-blocking.
