# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  flow_tracking:
    type: dict
    keys:
      sampled:
        type: dict
        $ref: "eos_cli_config_gen#/$defs/flow_tracking"
        keys:
          sample:
            type: int
            convert_types:
              - str
            min: 1
            max: 4294967295
          hardware_offload:
            type: dict
            keys:
              ipv4:
                type: bool
                description: Configure hardware offload for IPv4 traffic.
              ipv6:
                type: bool
                description: Configure hardware offload for IPv6 traffic.
              threshold_minimum:
                type: int
                convert_types:
                  - str
                min: 1
                max: 4294967295
                description: Minimum number of samples.
          trackers:
            type: list
            primary_key: name
            items:
              type: dict
              keys:
                table_size:
                  type: int
                  convert_types:
                    - str
                  min: 1
                  max: 614400
                  description: |
                    Maximum number of entries in flow table.
                record_export:
                  type: dict
                  keys:
                    mpls:
                      type: bool
                      description: Export MPLS forwarding information
      hardware:
        type: dict
        $ref: "eos_cli_config_gen#/$defs/flow_tracking"
