# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  platform:
    type: dict
    description: |-
      Every key below this point is platform dependent.
    keys:
      trident:
        type: dict
        keys:
          forwarding_table_partition:
            type: str
            convert_types:
              - int
          mmu:
            type: dict
            description: |
              Memory Management Unit settings.
            keys:
              active_profile:
                type: str
                description: |
                  The queue profile to be applied to the platform.
              queue_profiles:
                type: list
                primary_key: name
                convert_types:
                  - dict
                items:
                  type: dict
                  keys:
                    name:
                      type: str
                    multicast_queues:
                      type: list
                      primary_key: id
                      convert_types:
                        - dict
                      items:
                        type: dict
                        keys:
                          id:
                            type: int
                            convert_types:
                              - str
                            required: true
                            min: 0
                            max: 7
                          unit:
                            type: str
                            valid_values: ["bytes", "cells"]
                            description: |
                              Unit to be used for the reservation value. If not specified, default is bytes.
                          reserved:
                            type: int
                            convert_types: ["str"]
                            description: |
                              Amount of memory that should be reserved for this
                              queue.
                          threshold:
                            type: str
                            convert_types:
                              - "int"
                            description: |
                              Dynamic Shared Memory threshold.
                          drop:
                            type: dict
                            keys:
                              precedence:
                                type: int
                                valid_values: [1, 2]
                                required: true
                              threshold:
                                type: str
                                required: true
                                convert_types:
                                  - "int"
                                description: |
                                  Drop Treshold. This value may also be fractions.
                                  Example: 7/8 or 3/4 or 1/2
                    unicast_queues:
                      type: list
                      primary_key: id
                      convert_types:
                        - dict
                      items:
                        type: dict
                        keys:
                          id:
                            type: int
                            convert_types:
                              - str
                            required: true
                            min: 0
                            max: 7
                          unit:
                            type: str
                            valid_values: ["bytes", "cells"]
                            description: |
                              Unit to be used for the reservation value. If not specified, default is bytes.
                          reserved:
                            type: int
                            convert_types: ["str"]
                            description: |
                              Amount of memory that should be reserved for this
                              queue.
                          threshold:
                            type: str
                            convert_types:
                              - "int"
                            description: |
                              Dynamic Shared Memory threshold.
                          drop:
                            type: dict
                            keys:
                              precedence:
                                type: int
                                valid_values: [1, 2]
                                required: true
                              threshold:
                                type: str
                                required: true
                                convert_types:
                                  - "int"
                                description: |
                                  Drop Treshold. This value may also be fractions.
                                  Example: 7/8 or 3/4 or 1/2
      sand:
        type: dict
        description: Most of the platform sand options are hardware dependent and optional
        keys:
          qos_maps:
            type: list
            items:
              type: dict
              keys:
                traffic_class:
                  type: int
                  min: 0
                  max: 7
                  convert_types:
                    - "str"
                to_network_qos:
                  type: int
                  min: 0
                  max: 63
                  convert_types:
                    - "str"
          lag:
            type: dict
            keys:
              hardware_only:
                type: bool
              mode:
                type: str
          forwarding_mode:
            type: str
          multicast_replication:
            type: dict
            keys:
              default:
                type: str
                valid_values: ["ingress", "egress"]
          mdb_profile:
            type: str
            description: "Sand platforms MDB Profile configuration. Note: l3-xxxl does not support MLAG."
            valid_values: [ "balanced", "balanced-xl", "l3", "l3-xl", "l3-xxl", "l3-xxxl" ]
      sfe:
        type: dict
        description: Sfe (Software Forwarding Engine) settings.
        keys:
          data_plane_cpu_allocation_max:
            type: int
            description: Maximum number of CPUs used for data plane traffic forwarding.
            convert_types:
              - str
            min: 1
            max: 128
