# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  qos:
    type: dict
    keys:
      map:
        type: dict
        keys:
          cos:
            type: list
            items:
              type: str
              description: |
                Example: "0 1 to traffic-class 1"
          dscp:
            type: list
            items:
              type: str
              description: |
                Example: "8 9 10 to traffic-class 1"
          exp:
            type: list
            items:
              type: str
              description: |
                Example "0 to traffic-class 0"
          traffic_class:
            type: list
            items:
              type: str
              description: |
                Example: "1 to dscp 32"
      rewrite_dscp:
        type: bool
      random_detect:
        type: dict
        description: Global random-detect settings
        keys:
          ecn:
            type: dict
            description: Global ECN Configuration
            keys:
              allow_non_ect:
                type: dict
                keys:
                  enabled:
                    type: bool
                    description: |-
                      Allow non-ect and set drop-precedence 1 in a policy map simultaneously.
                      Check which command is required for your platform.
                  chip_based:
                    type: bool
                    description: Allow non-ect chip-based
