# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  queue_monitor_streaming:
    type: dict
    keys:
      enable:
        type: bool
      ip_access_group:
        type: str
        description: Name of IP ACL
      ipv6_access_group:
        type: str
        description: Name of IPv6 ACL
      max_connections:
        type: int
        convert_types:
          - str
        min: 1
        max: 100
      vrf:
        type: str
        convert_types:
          - int
