# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  router_multicast:
    type: dict
    keys:
      ipv4:
        type: dict
        keys:
          counters:
            type: dict
            keys:
              rate_period_decay:
                description: Rate in seconds
                type: int
                min: 0
                max: 600
                convert_types:
                  - str
          routing:
            type: bool
          multipath:
            type: str
            valid_values: ["none", "deterministic", "deterministic color", "deterministic router-id"]
          software_forwarding:
            type: str
            valid_values: ["kernel", "sfe"]
          rpf:
            type: dict
            keys:
              routes:
                type: list
                items:
                  type: dict
                  keys:
                    source_prefix:
                      description: Source address A.B.C.D or Source prefix A.B.C.D/E
                      type: str
                      required: true
                    destinations:
                      type: list
                      required: true
                      items:
                        type: dict
                        keys:
                          nexthop:
                            description: Next-hop IP address or interface name
                            type: str
                            required: true
                          distance:
                            description: Administrative distance for this route
                            type: int
                            min: 1
                            max: 255
                            convert_types:
                              - str
      vrfs:
        type: list
        primary_key: name
        items:
          type: dict
          keys:
            name:
              type: str
              convert_types:
                - int
            ipv4:
              type: dict
              keys:
                routing:
                  type: bool
