# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  router_l2_vpn:
    type: dict
    keys:
      arp_learning_bridged:
        type: bool
      arp_proxy:
        type: dict
        keys:
          prefix_list:
            type: str
            description: Prefix-list name. ARP Proxying is disabled for IPv4 addresses defined in the prefix-list.
      arp_selective_install:
        type: bool
      nd_learning_bridged:
        type: bool
      nd_proxy:
        type: dict
        keys:
          prefix_list:
            type: str
            description: Prefix-list name. ND Proxying is disabled for IPv6 addresses defined in the prefix-list.
      nd_rs_flooding_disabled:
        type: bool
      virtual_router_nd_ra_flooding_disabled:
        type: bool
