# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  stun:
    type: dict
    description: STUN configuration.
    keys:
      client:
        type: dict
        description: STUN client settings.
        keys:
          server_profiles:
            type: list
            description: List of server profiles for the client.
            primary_key: name
            items:
              type: dict
              keys:
                name:
                  type: str
                ip_address:
                  type: str
                ssl_profile:
                  type: str
                  description: SSL profile name.
                port:
                  type: int
                  description: Destination port for the request STUN server (default - 3478).
                  min: 1
                  max: 65535
                  convert_types:
                    - str
      server:
        type: dict
        description: STUN server settings.
        keys:
          local_interface:
            type: str
            deprecation:
              warning: true
              new_key: local_interfaces
              remove_in_version: v5.0.0
          local_interfaces:
            type: list
            min_length: 1
            items:
              type: str
          bindings_timeout:
            type: int
            description: Timeout for bindings stored on STUN server in seconds.
            convert_types:
              - str
            min: 10
            max: 7200
          ssl_profile:
            type: str
            description: SSL profile name.
          ssl_connection_lifetime:
            type: dict
            description: |-
              SSL connection lifetime in minutes or hours.
              If both are specified, minutes is given higher precedence.
            keys:
              minutes:
                type: int
                description: SSL connection lifetime in minutes (default - 120).
                convert_types:
                  - str
                min: 1
                max: 1440
              hours:
                type: int
                description: SSL connection lifetime in hours (default - 2).
                convert_types:
                  - str
                min: 1
                max: 24
          port:
            type: int
            description: Listening port for STUN server (default - 3478).
            min: 1
            max: 65535
            convert_types:
              - str
