# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  tacacs_servers:
    type: dict
    keys:
      timeout:
        type: int
        convert_types:
          - str
        description: Timeout in seconds
        min: 1
        max: 1000
      hosts:
        type: list
        items:
          type: dict
          keys:
            host:
              type: str
              description: Host IP address or name
            vrf:
              type: str
              convert_types:
                - int
            key:
              type: str
              description: Encrypted key
            key_type:
              type: str
              convert_types:
                - int
              valid_values: ["0", "7", "8a"]
              default: "7"
            single_connection:
              type: bool
            timeout:
              type: int
              convert_types:
                - str
              description: Timeout in seconds
              min: 1
              max: 1000
      policy_unknown_mandatory_attribute_ignore:
        type: bool
