# DC1 Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
# SVI Profile
svi_profiles:
  - profile: GENERIC
    mtu: 1560
    enabled: true
  - profile: GENERIC_FULL
    name: GENERIC Name
    mtu: 1560
    enabled: false
    ip_address_virtual: 10.1.10.254/24
  - profile: GENERIC_FULL_V6
    name: GENERIC Name V6
    mtu: 1560
    enabled: false
    ipv6_address_virtuals:
      - 2001:db8:451::1/64
  - profile: GENERIC_DUAL_STACK
    name: GENERIC DUAL STACK v4 and v6
    mtu: 1560
    enabled: false
    ip_address_virtual: 10.4.12.254/24
    ipv6_address_virtuals:
      - 2001:db8:412::1/64
    ipv6_enable: false
  - profile: TEST_SVI_NODE_INHERIT
    name: Test the SVI and node config inheritance
    mtu: 1560
    enabled: false
    ip_address_virtual: 10.4.13.254/24
    ipv6_address_virtuals:
      - 2001:db8:413::1/64
    ip_helpers:
      - ip_helper: 1.1.1.1
        source_interface: lo101
        source_vrf: TEST
    nodes:
      - node: evpn_services_l2_only_false
        ip_address: 12.4.13.2/24
        ipv6_address: 2012:db9:413::2/64
        ip_virtual_router_addresses: [ "12.4.13.1" ]
        ipv6_virtual_router_addresses: [ "2012:db9:413::1" ]
  - profile: GENERIC_DHCP
    mtu: 1560
    enabled: false
    ip_helpers:
      - ip_helper: 2.2.2.2
        source_interface: lo101
        source_vrf: MGMT
  - profile: WITH_NO_MTU
    enabled: true
  - profile: WITH_DHCP_AND_SNOOPING
    enabled: true
    ip_address_virtual: 10.1.11.254/24
    igmp_snooping_enabled: false
    ip_helpers:
      - ip_helper: 1.1.1.1
        source_interface: lo100
        source_vrf: TEST
  - profile: WITH_DHCP
    enabled: true
    ip_helpers:
      - ip_helper: 1.1.1.1
        source_interface: lo100
        source_vrf: MGMT
  - profile: DERIVED_DHCP
    parent_profile: GENERIC_DHCP
    enabled: true

network_services_keys:
  - name: tenant_a
  - name: tenant_b
  - name: tenant_c
  - name: tenant_d
