tenant_b:
  - name: Tenant_B
    mac_vrf_vni_base: 20000
    vrfs:
      - name: Tenant_B_OP_Zone
        vrf_vni: 20
        svis:
          - id: 210
            name: Tenant_B_OP_Zone_1
            tags: ['opzone']
            enabled: True
            ip_address_virtual: 10.2.10.1/24
          - id: 211
            name: Tenant_B_OP_Zone_2
            tags: ['opzone']
            enabled: True
            ip_address_virtual: 10.2.11.1/24
      - name: Tenant_B_WAN_Zone
        vrf_vni: 21
        evpn_l2_multi_domain: false
        svis:
          - id: 250
            name: Tenant_B_WAN_Zone_1
            tags: ['wan']
            enabled: True
            ip_address_virtual: 10.2.50.1/24
