hostname: inband-mgmt-subnet-vrf
is_deployed: true
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
- name: INBANDMGMT
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer: inband-mgmt-parent
  peer_interface: Ethernet22
  peer_type: l3leaf
  description: INBAND-MGMT-PARENT_Ethernet22
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: inband-mgmt-parent-vrf
  peer_interface: Ethernet22
  peer_type: l3leaf
  description: INBAND-MGMT-PARENT-VRF_Ethernet22
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
port_channel_interfaces:
- name: Port-Channel1
  description: INBAND-MGMT-PARENT_Po22
  type: switched
  shutdown: false
  mode: trunk
  vlans: '102'
ip_igmp_snooping:
  globally_enabled: true
vlans:
- id: 102
  tenant: system
  name: INBAND_MGMT
vlan_interfaces:
- name: Vlan102
  description: Inband Management
  shutdown: false
  mtu: 1500
  vrf: INBANDMGMT
  ip_address: 192.168.102.5/24
  type: inband_mgmt
static_routes:
- destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.102.1
  vrf: INBANDMGMT
