hostname: mgmt_interface_description
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 1.1.1.1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: Custom Management Interface Description
  shutdown: false
  vrf: MGMT
  ip_address: 1.1.1.2
  gateway: 1.1.1.1
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ip_igmp_snooping:
  globally_enabled: true
