hostname: mgmt_interface_ipv6
is_deployed: true
ipv6_static_routes:
- vrf: MGMT
  destination_address_prefix: ::/0
  gateway: 0200::1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
  ipv6_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: null
  gateway: null
  type: oob
  ipv6_enable: true
  ipv6_address: 0200::105/64
  ipv6_gateway: 0200::1
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ip_igmp_snooping:
  globally_enabled: true
