hostname: ntp-settings-2
is_deployed: true
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
- name: INBAND_MGMT
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ntp:
  local_interface:
    name: Vlan4092
    vrf: INBAND_MGMT
  servers:
  - name: 10.10.10.1
    vrf: INBAND_MGMT
    preferred: true
  - name: 10.10.10.2
    vrf: INBAND_MGMT
ip_igmp_snooping:
  globally_enabled: true
vlans:
- id: 4092
  tenant: system
  name: INBAND_MGMT
vlan_interfaces:
- name: Vlan4092
  description: Inband Management
  shutdown: false
  mtu: 1500
  vrf: INBAND_MGMT
  ip_address: 192.168.1.2/24
  type: inband_mgmt
