hostname: OVERLAY_ROUTING_PROTOCOL_CVX_SERVER1
is_deployed: true
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: none
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.254.254/23
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
cvx:
  shutdown: false
  peer_hosts:
  - 192.168.254.255
  services:
    vxlan:
      shutdown: false
