hostname: ptp-tests-l2leaf2-ptp-enabled
metadata:
  platform: vEOS-lab
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ptp:
  mode: boundary
  clock_identity: 00:1C:73:7f:00:02
  priority1: 127
  priority2: 2
  domain: 127
  monitor:
    enabled: true
    threshold:
      offset_from_master: 250
      mean_path_delay: 1500
    missing_message:
      sequence_ids:
        enabled: true
        announce: 3
        delay_resp: 3
        follow_up: 3
        sync: 3
ethernet_interfaces:
- name: Ethernet1
  peer: ptp-tests-leaf1
  peer_interface: Ethernet12
  peer_type: l3leaf
  description: PTP-TESTS-LEAF1_Ethernet12
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: ptp-tests-leaf2
  peer_interface: Ethernet12
  peer_type: l3leaf
  description: PTP-TESTS-LEAF2_Ethernet12
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
port_channel_interfaces:
- name: Port-Channel1
  description: PTP-TEST-LEAF_Po12
  type: switched
  shutdown: false
  mode: trunk
  vlans: '11'
  ptp:
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    transport: ipv4
    enable: true
vlans:
- id: 11
  name: VLAN11
  tenant: PTP
ip_igmp_snooping:
  globally_enabled: true
