hostname: ptp-tests-l2leaf1-ptp-disabled
metadata:
  platform: vEOS-lab
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ptp: {}
ethernet_interfaces:
- name: Ethernet1
  peer: ptp-tests-leaf1
  peer_interface: Ethernet11
  peer_type: l3leaf
  description: PTP-TESTS-LEAF1_Ethernet11
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: ptp-tests-leaf2
  peer_interface: Ethernet11
  peer_type: l3leaf
  description: PTP-TESTS-LEAF2_Ethernet11
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
port_channel_interfaces:
- name: Port-Channel1
  description: PTP-TEST-LEAF_Po11
  type: switched
  shutdown: false
  mode: trunk
  vlans: '11'
vlans:
- id: 11
  name: VLAN11
  tenant: PTP
ip_igmp_snooping:
  globally_enabled: true
