hostname: trunk-group-tests-l2leaf1a
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 1.1.1.1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
spanning_tree:
  no_spanning_tree_vlan: '4094'
vlans:
- id: 4094
  tenant: system
  name: MLAG_PEER
  trunk_groups:
  - MLAG
- id: 100
  name: svi100_with_trunk_groups
  tenant: TRUNK_GROUP_TESTS
  trunk_groups:
  - MLAG
  - TG_100
  - TG_NOT_MATCHING_ANY_SERVERS
  - UPLINK
- id: 200
  name: svi200_with_trunk_groups
  tenant: TRUNK_GROUP_TESTS
  trunk_groups:
  - MLAG
  - TG_200
  - TG_NOT_MATCHING_ANY_SERVERS
  - UPLINK
- id: 300
  name: svi300_with_trunk_groups
  tenant: TRUNK_GROUP_TESTS
  trunk_groups:
  - MLAG
  - TG_300
  - TG_NOT_MATCHING_ANY_SERVERS
  - UPLINK
- id: 398
  name: svi398_without_trunk_groups
  tenant: TRUNK_GROUP_TESTS
  trunk_groups:
  - MLAG
  - UPLINK
- id: 110
  name: l2vlan110_with_trunk_groups
  tenant: TRUNK_GROUP_TESTS
  trunk_groups:
  - MLAG
  - TG_100
  - TG_NOT_MATCHING_ANY_SERVERS
  - UPLINK
- id: 210
  name: l2vlan210_with_trunk_groups
  tenant: TRUNK_GROUP_TESTS
  trunk_groups:
  - MLAG
  - TG_200
  - TG_NOT_MATCHING_ANY_SERVERS
  - UPLINK
- id: 310
  name: l2vlan310_with_trunk_groups
  tenant: TRUNK_GROUP_TESTS
  trunk_groups:
  - MLAG
  - TG_300
  - TG_NOT_MATCHING_ANY_SERVERS
  - UPLINK
- id: 399
  name: l2vlan399_without_trunk_groups
  tenant: TRUNK_GROUP_TESTS
  trunk_groups:
  - MLAG
  - UPLINK
vlan_interfaces:
- name: Vlan4094
  description: MLAG_PEER
  shutdown: false
  ip_address: 10.255.248.0/31
  no_autostate: true
  mtu: 9214
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_PEER_trunk-group-tests-l2leaf1b_Po3
  type: switched
  shutdown: false
  mode: trunk
  trunk_groups:
  - MLAG
- name: Port-Channel1
  description: TRUNK_GROUP_TESTS_L3LEAF1_Po1
  type: switched
  shutdown: false
  mode: trunk
  trunk_groups:
  - UPLINK
  mlag: 1
- name: Port-Channel13
  description: server_with_tg_300_portchannel
  type: switched
  shutdown: false
  mode: trunk
  trunk_groups:
  - TG_NOT_MATCHING_ANY_VLANS
  - TG_300
  mlag: 13
ethernet_interfaces:
- name: Ethernet3
  peer: trunk-group-tests-l2leaf1b
  peer_interface: Ethernet3
  peer_type: mlag_peer
  description: MLAG_PEER_trunk-group-tests-l2leaf1b_Ethernet3
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 3
    mode: active
- name: Ethernet4
  peer: trunk-group-tests-l2leaf1b
  peer_interface: Ethernet4
  peer_type: mlag_peer
  description: MLAG_PEER_trunk-group-tests-l2leaf1b_Ethernet4
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 3
    mode: active
- name: Ethernet1
  peer: trunk-group-tests-l3leaf1a
  peer_interface: Ethernet1
  peer_type: l3leaf
  description: TRUNK-GROUP-TESTS-L3LEAF1A_Ethernet1
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: trunk-group-tests-l3leaf1b
  peer_interface: Ethernet1
  peer_type: l3leaf
  description: TRUNK-GROUP-TESTS-L3LEAF1B_Ethernet1
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet13
  peer: server_with_tg_300
  peer_interface: Nic3
  peer_type: server
  description: server_with_tg_300_Nic3
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 13
    mode: active
mlag_configuration:
  domain_id: TRUNK_GROUP_TESTS_L2LEAF1
  local_interface: Vlan4094
  peer_address: 10.255.248.1
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
ip_igmp_snooping:
  globally_enabled: true
