hostname: uplink-native-vlan-parent
is_deployed: true
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
vlans:
- id: 200
  name: NATIVE
  state: suspend
- id: 100
  name: NETWORK_SERVICES_VLAN
  tenant: test
ethernet_interfaces:
- name: Ethernet1
  peer: uplink-native-vlan-grandparent
  peer_interface: Ethernet1
  peer_type: l2leaf
  description: UPLINK-NATIVE-VLAN-GRANDPARENT_Ethernet1
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: uplink-native-vlan-child
  peer_interface: Ethernet2
  peer_type: l2leaf
  description: UPLINK-NATIVE-VLAN-CHILD_Ethernet2
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 2
    mode: active
port_channel_interfaces:
- name: Port-Channel1
  description: UPLINK-NATIVE-VLAN-GRANDPARENT_Po1
  type: switched
  shutdown: false
  mode: trunk
  native_vlan: 100
  vlans: '100'
- name: Port-Channel2
  description: UPLINK-NATIVE-VLAN-CHILD_Po2
  type: switched
  shutdown: false
  mode: trunk
  native_vlan: 200
  vlans: '100'
ip_igmp_snooping:
  globally_enabled: true
