hostname: UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1A
metadata:
  platform: vEOS-LAB
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.5
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
  no_spanning_tree_vlan: '4094'
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.201.201/24
  gateway: 192.168.200.5
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
vlans:
- id: 4094
  tenant: system
  name: MLAG_PEER
  trunk_groups:
  - MLAG
vlan_interfaces:
- name: Vlan4094
  description: MLAG_PEER
  shutdown: false
  ip_address: 10.255.252.0/31
  no_autostate: true
  mtu: 9214
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_PEER_UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1B_Po3
  type: switched
  shutdown: false
  mode: trunk
  trunk_groups:
  - MLAG
  storm_control:
    broadcast:
      level: '25'
    unknown_unicast:
      level: '25'
  native_vlan_tag: true
- name: Port-Channel1
  description: DC1_LEAF1_Po5
  type: switched
  shutdown: false
  mode: trunk
  vlans: none
  mlag: 1
  storm_control:
    broadcast:
      level: '25'
    unknown_unicast:
      level: '25'
  native_vlan_tag: true
ethernet_interfaces:
- name: Ethernet3
  peer: UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1B
  peer_interface: Ethernet3
  peer_type: mlag_peer
  description: MLAG_PEER_UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1B_Ethernet3
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 3
    mode: active
- name: Ethernet4
  peer: UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1B
  peer_interface: Ethernet4
  peer_type: mlag_peer
  description: MLAG_PEER_UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1B_Ethernet4
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 3
    mode: active
- name: Ethernet1
  peer: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1A
  peer_interface: Ethernet5
  peer_type: l3leaf
  description: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1A_Ethernet5
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B
  peer_interface: Ethernet5
  peer_type: l3leaf
  description: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B_Ethernet5
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
mlag_configuration:
  domain_id: UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1
  local_interface: Vlan4094
  peer_address: 10.255.252.1
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
ip_igmp_snooping:
  globally_enabled: true
