hostname: uplink-native-vlan-grandparent
is_deployed: true
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer: uplink-native-vlan-parent
  peer_interface: Ethernet1
  peer_type: l2leaf
  description: UPLINK-NATIVE-VLAN-PARENT_Ethernet1
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
port_channel_interfaces:
- name: Port-Channel1
  description: UPLINK-NATIVE-VLAN-PARENT_Po1
  type: switched
  shutdown: false
  mode: trunk
  native_vlan: 100
  vlans: '100'
vlans:
- id: 100
  name: NETWORK_SERVICES_VLAN
  tenant: test
ip_igmp_snooping:
  globally_enabled: true
