loopback_ipv4_pool: 192.168.0.0/24

type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: connected-endpoints-phone-vlan-mode

servers:
  # port-channel provide physical and individual port-channel descriptions
  - name: OLD_SW-1/7
    adapters:
      - switches: [connected-endpoints-phone-vlan-mode, connected-endpoints-phone-vlan-mode]
        switch_ports: [Ethernet9, Ethernet10]
        mode: trunk
        phone_vlan: 333
        native_vlan: 123

expected_error_message: "Setting 'phone_vlan' requires 'mode: trunk phone' to be set on connected endpoint 'OLD_SW-1/7'."
