---
# Minimum config to only test the specific feature.
node_type_keys:
  - key: pe
    type: pe
    mpls_lsr: true
    default_mpls_overlay_role: client
    default_evpn_role: client
    network_services:
      l1: true
      l2: true
      l3: true
    default_overlay_routing_protocol: ibgp
    default_overlay_address_families: [ evpn ]
    default_evpn_encapsulation: mpls

pe:
  defaults:
    loopback_ipv4_pool: 10.42.0.0/24
    bgp_as: 42
  nodes:
    - name: duplicate-l3-interfaces-network-services
      id: 42

type: pe
design:
  type: mpls

tenants:
  - name: TENANT_B
    vrfs:
      - name: TENANT_B_WAN
        vrf_id: 20
        l3_interfaces:
          - description: TENANT_B_SITE_3_OSPF
            enabled: true
            interfaces:
              - Ethernet6.101
            ip_addresses:
              - 192.168.48.4/31
            nodes:
              - duplicate-l3-interfaces-network-services
          - description: TENANT_B_SITE_5
            enabled: true
            # duplicate interfaces
            interfaces:
              - Ethernet6.101
            ip_addresses:
              - 192.168.48.2/31
            nodes:
              - duplicate-l3-interfaces-network-services

expected_error_message: >-
  Found duplicate objects with conflicting data while generating configuration for Ethernet Interfaces defined under l3_interfaces.
  {'name': 'Ethernet6.101', 'vrf': 'TENANT_B_WAN', 'description': 'TENANT_B_SITE_5', 'ip_address': '192.168.48.2/31'} conflicts with
  {'name': 'Ethernet6.101', 'vrf': 'TENANT_B_WAN', 'description': 'TENANT_B_SITE_3_OSPF', 'ip_address': '192.168.48.4/31'}.
