---
type: spine

spine:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 10.255.0.0/27
    bgp_as: 65100
    bgp_defaults:
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart

  nodes:
    # This is the uplink switch for node-group "duplicate-ip-address-router-bgp"
    - name: duplicate-ip-address-uplink-switch-router-bgp
      id: 1
      mgmt_ip: 172.16.1.11/24

expected_error_message: >-
  Found duplicate objects with conflicting data while generating configuration for IP address defined under BGP neighbor for
  underlay. {'ip_address': '10.255.255.3', 'peer_group': 'IPv4-UNDERLAY-PEERS', 'description': 'duplicate-ip-address-2_Ethernet1', 'peer': 'duplicate-ip-address-2'}
  conflicts with {'ip_address': '10.255.255.3', 'peer_group': 'IPv4-UNDERLAY-PEERS', 'description': 'duplicate-ip-address-1_Ethernet1', 'peer': 'duplicate-ip-address-1'}.
