---
# Minimum config to only test the specific feature.
l3leaf:
  defaults:
    loopback_ipv4_pool: 10.42.0.0/24
    bgp_as: 42
    vtep_loopback_ipv4_pool: 10.43.0.0/24
  nodes:
    - name: duplicate-vni-l3-interfaces-in-vxlan-interface
      id: 42

type: l3leaf

tenants:
  - name: Tenant_A
    mac_vrf_vni_base: 1000
    mac_vrf_id_base: 20000
    vrfs:
      - name: Tenant_A_OP_Zone
        description: "Tenant_A_OP_Zone"
        vrf_vni: 10
        svis:
          - id: '10'
            name: Tenant_A_OP_Zone_1

      - name: Tenant_A_WAN_Zone
        vrf_id: 1010
        l3_interfaces:
          - interfaces: [ Ethernet7 ]
            ip_addresses: [ 10.10.10.10/24 ]
            nodes: [ duplicate-vni-l3-interfaces-in-vxlan-interface ]
            mtu: 9000
            enabled: True
            description: "test"

expected_error_message: "Found duplicate objects with conflicting data while generating configuration for VXLAN VNIs for VRFs. {'id': None, 'name': 'Tenant_A_WAN_Zone', 'vni': 1010} conflicts with {'id': 10, 'name': None, 'vni': 1010}."
