type: l2leaf
l2leaf:
  nodes:
    - name: source-interfaces-ssh-client-duplicate-vrf
      id: 1
      mgmt_ip: 192.168.0.2/24
      inband_mgmt_ip: 10.20.30.40/24
      inband_mgmt_gateway: 10.20.30.1
      # inband_mgmt_vrf: default

mgmt_interface_vrf: default

source_interfaces:
  ssh_client:
    mgmt_interface: true
    inband_mgmt_interface: true

expected_error_message: >-
  Unable to configure multiple IP SSH Client source-interfaces for the same VRF 'default'.
