---
underlay_routing_protocol: ospf
mlag_support: true

type: l3leaf

l3leaf:
  defaults:
    mlag_peer_vlan: 4094
    mlag_peer_l3_vlan: 4094
    mlag_peer_ipv4_pool: 10.10.255.0/24
    uplink_ipv4_pool: 10.10.101.0/24
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 32
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    platform: vEOS-LAB
    uplink_switches: ["DC1-SPINE1"]
    uplink_interfaces: ["Ethernet1"]
  node_groups:
    - group: MLAG_OSPF_L3LEAF1
      nodes:
        - name: MLAG-OSPF-L3LEAF1A
          id: 4
          bgp_as: 65161
          mgmt_ip: 192.168.201.114/24
          uplink_switch_interfaces: [Ethernet18]
          mlag_interfaces: [Ethernet5, Ethernet6]
        - name: MLAG-OSPF-L3LEAF1B
          id: 5
          bgp_as: 65161
          mgmt_ip: 192.168.201.115/24
          uplink_switch_interfaces: [Ethernet220]
          mlag_interfaces: [Ethernet5, Ethernet6]
