type: l2leaf
mgmt_gateway: 192.168.0.1

port_profiles:
  - profile: common
    mode: access
    vlans: "999"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: enabled

  - profile: ap_with_port_channel
    parent_profile: common
    vlans: "101"
    port_channel:
      mode: active

  - profile: pc
    parent_profile: common
    vlans: "100"

    # Test phone_vlan with only_vlans_in_use
  - profile: phone_with_pc
    mode: trunk phone
    phone_vlan: 300
    native_vlan: 100
    phone_trunk_mode: untagged

network_ports:
  - switches:
      - network-ports-tests.1
    switch_ports:
      - Ethernet1-2
    profile: pc
    description: PCs

  - switches:
      - network-ports-tests-2$
    switch_ports:
      - Ethernet1-2
    profile: ap_with_port_channel
    description: AP1 with port_channel

  - switches:
      - network-ports-[est]{5}[-.].*
    switch_ports:
      - Ethernet3-4
      - Ethernet2/1-48
    profile: pc
    description: PCs

  - switches:
      - network-ports-tests-2
    switch_ports:
      - Ethernet11-12
    profile: phone_with_pc
    description: Phones with attached PCs

  # Test for issue #2223 regarding colon in description
  - switches:
      - network-ports-tests.1
    switch_ports:
      - Ethernet5-6
    description: "N: blah"

  - switches:
      - network-ports-tests.2
    switch_ports:
      - Ethernet7-10
    description: "Checking port-channels"
    port_channel:
      channel_id: 42
      mode: "active"

  # The next entries are used to test the duplicate check feature together with the
  # CONNECTED_ENDPOINT_OVERWRITING_NETWORK_PORT below.
  - switches:
      - network-ports-tests.1
    switch_ports:
      - Ethernet11-14
    description: Base config which may be overwritten

  - switches:
      - network-ports-tests.1
    switch_ports:
      - Ethernet12
    description: Config overwriting base config

servers:
  - name: CONNECTED_ENDPOINT_OVERWRITING_NETWORK_PORT
    adapters:
      - endpoint_ports: [Eth42]
        switch_ports: [Ethernet14]
        switches: [network-ports-tests.1]

# Only creating network services required to test the filter "only_vlans_in_use" combined with network ports
tenants:
  - name: TEST
    l2vlans:
      # Vlan 100 will be configured on both devices since it is in use
      - id: 100
        name: VLAN100_ON_L2LEAF_1_AND_2
      # Vlan 200 will only be configured on L2LEAF_1 since it is not in use
      - id: 200
        name: VLAN200_ON_L2LEAF_1_ONLY
      # VLAN 300 will be configured on network-ports-tests-1 by default, and
      # network-ports-tests-2 using only_vlans_in_use
      - id: 300
        name: VLAN300_PHONE_ON_L2LEAF1_AND_2

l2leaf:
  node_groups:
    - group: mlag
      mlag_peer_ipv4_pool: 10.255.252.0/24
      mlag_interfaces: ["Ethernet10/1"]
      nodes:
        - name: network-ports-tests.1
          id: 1
        - name: network-ports-tests-2
          filter:
            only_vlans_in_use: true
          id: 2
