---
type: l3leaf
l3leaf:
  defaults:
    mlag_peer_ipv4_pool: 10.10.255.0/24
    mlag_peer_l3_ipv4_pool: 10.10.224.0/24
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 32
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    platform: vEOS-LAB
    mlag_interfaces: [Ethernet5, Ethernet6]
  node_groups:
    - group: OVERRIDE_VTEP_L3LEAF1
      bgp_as: 923
      vtep: false
      nodes:
        - name: OVERRIDE_VTEP_L3LEAF1A
          id: 3
          mgmt_ip: 192.168.201.116/24
          vtep: true
        - name: OVERRIDE_VTEP_L3LEAF1B
          id: 4
          mgmt_ip: 192.168.201.117/24
