type: l3leaf
l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    virtual_router_mac_address: 00:dc:00:00:00:0a
    uplink_ipv4_pool: 192.168.153.0/24
  nodes:
    - name: underlay_filter_peer_as_evpn_1
      bgp_as: 64512
      id: 1
      uplink_switches: [ underlay_filter_peer_as_evpn_2, underlay_filter_peer_as_evpn_3 ]
      uplink_interfaces: [ Ethernet1, Ethernet2 ]
      uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
      evpn_role: client
    - name: underlay_filter_peer_as_evpn_2
      bgp_as: 64513
      id: 2
      evpn_role: server
    - name: underlay_filter_peer_as_evpn_3
      bgp_as: 64513
      id: 3
      evpn_role: server

underlay_filter_peer_as: true
