# Testing "connected_endpoints_keys" as dict of dict
# Dict type is deprecated in 4.0.0. To be removed in 5.0.0
connected_endpoints_keys:
  servers:
    type: server
  firewalls:
    type: firewall
  routers:
    type: router
  load_balancers:
    type: load_balancer
  storage_arrays:
    type: storage_array
