servers:
  - name: server01_ESI
    rack: RackC
    adapters:
      - endpoint_ports: [ Eth1, Eth2]
        switch_ports: [ Ethernet12, Ethernet12]
        switches: [ host1, Leaf1]
        profile: TENANT_A_B
        # Testing "port_channel" with "short_esi"
        # "port_channel.short_esi" is deprecated in 4.0.0. To be removed in 5.0.0
        port_channel:
          description: PortChanne1
          mode: active
          short_esi: '0303:0202:0101'
      - endpoint_ports: [ Eth6, Eth7 ]
        switch_ports: [ Ethernet13, Ethernet13 ]
        switches: [ host1, DC1-LEAF2B ]
        mtu: 1601
        ethernet_segment:
          short_esi: '0303:0202:0102'
        # Testing "port_channel" with "short_esi" when "ethernet_segment.short_esi" is defined
        # "port_channel.short_esi" is deprecated in 4.0.0. To be removed in 5.0.0
        port_channel:
          description: PortChanne1
          mode: active
          short_esi: '0303:0202:0101'
