---
- name: Converge
  hosts: EOS_DESIGNS_DEPRECATED_VARS
  gather_facts: false
  connection: local
  tasks:

    - name: Generate intended variables
      delegate_to: 127.0.0.1
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
