# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
  # handlers file for eos_config_deploy_eapi

- name: Backup running config
  arista.eos.eos_config:
    backup: yes
    backup_options:
      filename: "{{ post_running_config_backup_filename }}"
      dir_path: "{{ post_running_config_backup_dir }}"
  listen: "backup config"
